In [3]:
import pandas as pd
from IPython.display import HTML

In [4]:
employees = pd.read_csv('employees.csv')
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [5]:
pd.DataFrame(employees)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [ ]:
# ver el dataframe completo

df = pd.read_csv('employees.csv')
HTML(df.to_html())

In [15]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 62.6+ KB

In [7]:
pd.to_datetime(employees['Start Date'])

0     1993-08-06
1     1996-03-31
2     1993-04-23
3     2005-03-04
4     1998-01-24
         ...
995   2014-11-23
996   1984-01-31
997   2013-05-20
998   2013-04-20
999   2012-05-15
Name: Start Date, Length: 1000, dtype: datetime64[ns]

In [ ]:
employees['Start Date'] = pd.to_datetime(employees['Start Date'], format="%m/%d/%Y")

In [ ]:
# Solo quiero el tiempo, no la fecha, por eso se agrega dt.time
employees['Last Login Time'] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time

In [17]:
employees['Senior Management'] = employees['Senior Management'].astype(bool)

In [19]:
employees['Gender'] = employees['Gender'].astype('category')

In [ ]:
# astype bool: convierte lo svalores de una columna a tipo booleano (true o False)
# astype int: convierte los valores de una columna a tipo entero
# astype category: asigna un codigo numerico a cada uno de estos valores unicos

In [20]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    category
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 49.1+ KB

In [5]:
import pandas as pd
employees = pd.read_csv('employees.csv', parse_dates=['Start Date'], date_format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees['Senior Management'] = employees['Senior Management'].astype(bool)
employees['Gender'] = employees['Gender'].astype('category')
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [23]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   datetime64[ns]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 55.8+ KB

In [25]:
"Male" == "Male"

True

In [28]:
#Seleccionar aquellos valores que en 'Gender' son igual a 'Male'
employees[employees['Gender'] == "Male"]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [37]:
employees[employees['Team'] == "Finance"]

#Misma forma pero con un codigo mas limpio
on_finance_team = employees['Team'] == "Finance"
# debe contener corchetes
employees[on_finance_team]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
14,Kimberly,Female,1999-01-14,07:13:00,41426,14.543,True,Finance
46,Bruce,Male,2009-11-28,10:47:00,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,1998-07-27,11:12:00,137144,10.081,False,Finance
954,Joe,Male,1980-01-19,04:06:00,119667,1.148,True,Finance
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [ ]:
# Filtar por 'Senior Managment' solo los valores true, por default se puede
employees[employees['Senior Management']]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [41]:
# Filtrar por valores
employees[employees['Salary']> 110000]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
...,...,...,...,...,...,...,...,...
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [6]:
import numpy as np
employees[employees['Bonus %'] < 1.5]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
58,Theresa,Female,2010-04-11,07:18:00,72670,1.481,True,Engineering
77,Charles,Male,2004-09-14,08:13:00,107391,1.260,True,Marketing
175,Willie,Male,1998-02-17,08:20:00,146651,1.451,True,Engineering
189,Clarence,Male,1998-05-02,03:16:00,85700,1.215,False,Sales
217,Douglas,Male,1999-09-03,04:00:00,83341,1.015,True,Client Services
273,Nicholas,Male,1994-04-12,08:21:00,74669,1.113,True,Product
279,Ruby,Female,2000-11-08,07:35:00,105946,1.139,False,Business Development
365,Gloria,NaN,1983-07-19,01:57:00,140885,1.113,False,Human Resources
445,Chris,Male,2006-12-12,01:57:00,71642,1.496,False,NaN
481,NaN,Female,2013-04-27,06:40:00,93847,1.085,True,Business Development
527,Helen,NaN,1993-12-02,01:42:00,45724,1.022,False,Product
570,Kelly,Female,1996-08-16,03:09:00,41427,1.431,False,Product
578,Amanda,Female,1982-03-17,11:46:00,107111,1.438,True,Product
579,Harold,Male,2010-10-18,08:45:00,65673,1.187,True,Legal
617,Kathy,Female,2001-01-14,05:11:00,45682,1.451,True,Marketing
618,Peter,Male,1992-11-24,05:43:00,69297,1.268,False,Finance
638,Frances,Female,1996-11-12,06:08:00,112467,1.433,False,Business Development
652,Willie,Male,2009-12-05,05:39:00,141932,1.017,True,Engineering
708,Steve,Male,2002-01-11,09:17:00,51821,1.197,True,Legal
732,Henry,Male,1986-05-12,02:04:00,59943,1.432,False,Finance
734,NaN,Female,1994-12-18,08:42:00,138807,1.400,True,Human Resources
746,Gloria,Female,2004-08-19,10:31:00,46602,1.027,True,Business Development
912,Joe,Male,1998-12-08,10:28:00,126120,1.020,False,NaN
929,Theresa,Female,2001-04-27,09:17:00,75661,1.079,True,Legal
954,Joe,Male,1980-01-19,04:06:00,119667,1.148,True,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product

In [10]:
import datetime as dt

In [ ]:
# Un filtro con fecha
employees[employees['Start Date'] < '1985-01-01']
# Empleados que se conectaron antes del mediodia
employees[employees['Last Login Time'] < dt.time(12,0,0)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [23]:
# Filter with more than One condition (AND)
employees = pd.read_csv('employees.csv', parse_dates=['Start Date'], date_format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees['Senior Management'] = employees['Senior Management'].astype(bool)
employees['Gender'] = employees['Gender'].astype('category')
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [59]:
# Mujeres que trabajan en Marketing
is_female = employees['Gender'] == 'Female'
is_in_marketing = employees['Team'] == 'Marketing'
salary_over_100k = employees['Salary'] > 100000

In [60]:
is_female & is_in_marketing & salary_over_100k
# True, True -> True
#'''Si es mujer pero no de marketing'''
#True, False -> False
#'''Si no es mujer pero si de marketing'''
#False, True -> False
#'''No es mujer pero tampoco de marketing'''
# False, False -> False

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [62]:
employees[is_female & is_in_marketing & salary_over_100k]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,01:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,08:45:00,114412,8.756,True,Marketing
305,Margaret,Female,1993-02-06,01:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,03:01:00,145988,18.243,False,Marketing
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
468,Janice,Female,1997-06-28,01:48:00,136032,10.696,True,Marketing
490,Judith,Female,2007-11-23,01:22:00,117055,7.461,False,Marketing
531,Virginia,Female,2010-05-02,09:10:00,123649,10.154,True,Marketing
585,Shirley,Female,1988-04-16,11:09:00,132156,2.754,False,Marketing
627,Anne,Female,1984-11-21,12:30:00,128305,16.636,False,Marketing
656,Lisa,Female,1982-02-09,06:44:00,113592,17.108,True,Marketing
675,Diane,Female,2009-10-30,06:56:00,130577,12.791,False,Marketing
676,Annie,Female,1992-06-06,10:04:00,138925,9.801,True,Marketing
811,Judith,Female,1989-09-03,11:16:00,134048,6.818,True,Marketing
813,Evelyn,Female,2002-02-10,04:44:00,123621,19.767,True,Marketing
881,Ruby,Female,1980-01-28,11:08:00,142868,6.318,False,Marketing
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing

In [12]:
#Filter with more than One Condition
# AND vs OR
#
# True, Tru -> True
# True, False -> True
# False, True -> True
# False, False -> False

#Employees who are either senior managment OR started before January 1, 1990

is_senior_management = employees["Senior Management"]
started_in_80s = employees['Start Date'] < "1990-01-01"

employees[is_senior_management | started_in_80s]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [13]:
# Roberto que trabaja en Servicio al Cliente o Start Date despues del primero de junio de 2016
is_Robert = employees['First Name'] == "Robert"
is_in_client_services = employees ['Team'] == 'Client Services'
start_date_after_june_2016 = employees['Start Date'] > '2016-06-01'

In [16]:
employees[(is_Robert & is_in_client_services) | start_date_after_june_2016]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
387,Robert,Male,1994-10-29,04:26:00,123294,19.894,False,Client Services
451,Terry,NaN,2016-07-15,12:29:00,140002,19.490,True,Marketing

In [1]:
#The isin method
#Legal Team or Sales Team or Product Team
# Se debe cumplir por lo menos una de estas tres condiciones

# Filter with more than One condition (AND)
import pandas as pd
employees = pd.read_csv('employees.csv', parse_dates=['Start Date'], date_format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees['Senior Management'] = employees['Senior Management'].astype(bool)
employees['Gender'] = employees['Gender'].astype('category')
employees.head()

legal = employees['Team'] == 'Legal'
sales = employees['Team'] == 'Sales'
product = employees['Team'] == 'Product'

employees[legal | sales | product]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [30]:
# Comprueba si este valor esta dentro de las listas
# Verifica si cada elemento de una serie o DF esta presente en un a lista o en otra serie. 
# Devuelve una serie booleana que inidca si (True) esta presente en la lista e indica si no lo esta (False)
employees[employees["Team"].isin(["Legal", "Sales", "Product"])]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [2]:
# The isnull and notnull Methods
employees = pd.read_csv('employees.csv', parse_dates=['Start Date'], date_format="%m/%d/%Y")
employees['Last Login Time'] = pd.to_datetime(employees["Last Login Time"], format="%H:%M %p").dt.time
employees['Senior Management'] = employees['Senior Management'].astype(bool)
employees['Gender'] = employees['Gender'].astype('category')
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [ ]:
# isnull va a marcar los valores NaN o los valores que faltan con true

# isnull se utiliza para determinar si un valor en un objeto de pandas es nulo o faltante, true = valor nulo, false = si no lo es
# notnull()  se utiliza para determinar si un calor en un objeto Pandas no es nulo ni faltante, true = si es lavlor no es nulo, false = si lo es

employees[employees['Team'].isnull()]
employees[employees['Team'].notnull()]

# Marco de datos filtrado donde se va a tener un valor nulo en la columna de nombre y valor presente en la columna equipo 
# solo se han seleccionado los empleados cuyo nombre falta pero tienen un equipo asignado.
employees[employees['First Name'].isnull() & employees['Team'].notnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
25,NaN,Male,2012-10-08,01:12:00,37076,18.576,True,Client Services
39,NaN,Male,2016-01-29,02:33:00,122173,7.797,True,Client Services
51,NaN,NaN,2011-12-17,08:29:00,41126,14.009,True,Sales
62,NaN,Female,2007-06-12,05:25:00,58112,19.414,True,Marketing
116,NaN,Male,1991-06-22,08:58:00,76189,18.988,True,Legal
149,NaN,Female,2014-08-17,02:00:00,86230,8.578,True,Distribution
157,NaN,Female,2005-07-27,08:32:00,79536,14.443,True,Product
165,NaN,Female,2014-03-23,01:28:00,59148,9.061,True,Legal
166,NaN,Female,1991-07-09,06:52:00,42341,7.014,True,Sales
174,NaN,NaN,2007-09-18,06:59:00,40297,6.185,True,Client Services
186,NaN,Female,2005-02-23,09:50:00,149654,1.825,True,Sales
220,NaN,Female,1991-06-17,12:49:00,71945,5.560,True,Marketing
253,NaN,NaN,2003-04-28,03:01:00,113732,10.391,True,Sales
257,NaN,Male,1999-11-25,06:16:00,42676,15.517,True,Sales
266,NaN,Female,2009-08-05,08:14:00,115145,14.063,True,Distribution
267,NaN,Male,2005-02-04,01:01:00,40451,16.044,True,Distribution
269,NaN,Female,1992-08-02,08:35:00,145316,18.517,True,Human Resources
320,NaN,Female,2008-07-08,11:40:00,62960,14.356,True,Sales
329,NaN,Male,2010-01-27,02:57:00,87760,14.987,True,Engineering
352,NaN,Male,2011-10-09,09:29:00,69906,4.844,True,Engineering
353,NaN,Male,1997-04-22,09:36:00,65078,3.095,True,Marketing
374,NaN,Female,2006-12-31,11:02:00,81444,3.171,True,Distribution
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
416,NaN,Male,2008-06-29,05:23:00,111043,5.966,True,Distribution
444,NaN,Male,2016-05-24,09:17:00,76409,7.008,True,Distribution
454,NaN,Male,1995-02-21,12:26:00,136602,10.429,True,Marketing
481,NaN,Female,2013-04-27,06:40:00,93847,1.085,True,Business Development
483,NaN,Female,1992-04-26,08:01:00,115436,3.099,True,Human Resources
504,NaN,Female,2014-06-24,10:05:00,38275,10.494,True,Distribution
505,NaN,Male,1980-04-20,01:17:00,71520,13.248,True,Engineering
521,NaN,NaN,1981-09-25,09:59:00,83895,17.971,True,Engineering
540,NaN,Female,2009-12-02,03:30:00,84746,4.820,True,Finance
574,NaN,Female,2009-01-13,01:01:00,118736,7.421,True,Client Services
599,NaN,Female,1990-10-11,10:57:00,98385,10.925,True,Human Resources
607,NaN,Male,1983-10-13,11:59:00,139754,12.740,True,Sales
608,NaN,Female,1993-10-24,05:17:00,116236,17.274,True,Engineering
628,NaN,NaN,1988-09-02,12:49:00,147309,1.702,True,Distribution
674,NaN,Male,2012-08-28,07:56:00,88733,1.932,True,Human Resources
685,NaN,Male,1989-10-20,09:37:00,88086,19.387,True,Finance
687,NaN,Male,1996-12-27,07:07:00,139959,8.992,True,Distribution
697,NaN,Male,1990-05-23,02:09:00,136655,9.801,True,Distribution
709,NaN,Male,1995-04-07,04:32:00,60411,12.048,True,Human Resources
733,NaN,Male,2009-06-17,01:00:00,136681,3.655,True,Business Development
734,NaN,Female,1994-12-18,08:42:00,138807,1.400,True,Human Resources
773,NaN,Male,1986-10-24,09:23:00,47176,10.736,True,Finance
782,NaN,Male,1986-05-06,04:41:00,74104,17.680,True,Client Services
783,NaN,NaN,1991-04-15,03:39:00,132505,13.592,True,Product
785,NaN,Female,1982-07-24,12:00:00,57811,8.941,True,Marketing
812,NaN,Male,1994-12-13,10:34:00,141311,5.478,True,Product
821,NaN,Female,1980-12-27,02:27:00,80399,12.254,True,Distribution
823,NaN,Male,2009-11-12,02:30:00,109411,9.494,True,Engineering
877,NaN,Male,1980-09-05,07:36:00,114896,13.823,True,Client Services
890,NaN,Male,2015-11-24,03:11:00,145329,7.100,True,Finance
902,NaN,Male,2001-05-23,07:52:00,103877,6.322,True,Distribution
925,NaN,Female,2000-08-23,04:19:00,95866,19.388,True,Sales
946,NaN,Female,1985-09-15,01:50:00,133472,16.941,True,Distribution
947,NaN,Male,2012-07-30,03:07:00,107351,5.329,True,Marketing

In [8]:
# The between method

# Se usa para filtrar filas de DF dentro de un iintervalo determinado

# quiero extraer a los empleados con un salario entre 130,000 

employees[employees['Salary'].between(60000,70000)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
20,Lois,NaN,1995-04-22,07:18:00,64714,4.934,True,Legal
41,Christine,NaN,2015-06-28,01:08:00,66582,11.308,True,Business Development
...,...,...,...,...,...,...,...,...
965,Catherine,Female,1989-09-25,01:31:00,68164,18.393,False,Client Services
970,Alice,Female,1988-09-03,08:54:00,63571,15.397,True,Product
974,Harry,Male,2011-08-30,06:31:00,67656,16.455,True,Client Services
978,Sean,Male,1983-01-17,02:23:00,66146,11.178,False,Human Resources
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development

In [9]:
employees[employees['Bonus %'].between(2.0,5.0)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
20,Lois,NaN,1995-04-22,07:18:00,64714,4.934,True,Legal
40,Michael,Male,2008-10-10,11:25:00,99283,2.665,True,Distribution
49,Chris,NaN,1980-01-24,12:13:00,113590,3.055,False,Sales
60,Paula,NaN,2005-11-23,02:01:00,48866,4.271,False,Distribution
...,...,...,...,...,...,...,...,...
943,Wayne,Male,2006-09-08,11:09:00,67471,2.728,False,Engineering
961,Antonio,NaN,1989-06-18,09:37:00,103050,3.050,False,Legal
976,Denise,Female,1992-10-19,05:42:00,137954,4.195,True,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing

In [10]:
# filtro between con tiempo

employees[employees['Start Date'].between('1991-01-01','1992-01-01')]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
27,Scott,NaN,1991-07-11,06:58:00,122367,5.218,False,Legal
75,Bonnie,Female,1991-07-02,01:27:00,104897,5.118,True,Human Resources
88,Donna,Female,1991-11-27,01:59:00,64088,6.155,True,Legal
116,NaN,Male,1991-06-22,08:58:00,76189,18.988,True,Legal
148,Patrick,NaN,1991-07-14,02:24:00,124488,14.837,True,Sales
166,NaN,Female,1991-07-09,06:52:00,42341,7.014,True,Sales
172,Sara,Female,1991-09-23,06:17:00,97058,9.402,False,Finance
220,NaN,Female,1991-06-17,12:49:00,71945,5.560,True,Marketing
245,Victor,Male,1991-04-11,07:44:00,70817,17.138,False,Engineering
277,Brenda,NaN,1991-05-29,06:32:00,82439,19.062,False,Sales
313,Judy,Female,1991-07-01,02:33:00,109510,13.457,True,Legal
328,Samuel,Male,1991-12-19,02:54:00,76076,5.319,True,Finance
339,Michael,Male,1991-11-22,12:57:00,98753,16.443,True,Human Resources
537,Cynthia,Female,1991-09-14,01:08:00,51633,13.472,True,Business Development
552,Barbara,Female,1991-09-02,03:41:00,127297,11.905,True,Product
603,Carl,NaN,1991-10-26,08:11:00,100888,12.490,True,Business Development
639,Amanda,NaN,1991-08-11,02:15:00,46665,19.391,True,Client Services
704,Thomas,Male,1991-09-07,09:51:00,65251,11.211,False,Distribution
725,Jeremy,Male,1991-05-19,01:40:00,131513,1.876,True,Finance
766,Justin,Male,1991-07-25,12:45:00,112975,9.699,False,Human Resources
771,Peter,Male,1991-05-22,01:39:00,102577,12.026,True,Product
783,NaN,NaN,1991-04-15,03:39:00,132505,13.592,True,Product
891,Timothy,Male,1991-08-25,10:37:00,92587,8.475,False,Finance
895,Janice,NaN,1991-11-19,06:02:00,139791,16.968,False,Business Development
909,Donald,Male,1991-08-01,02:25:00,61999,6.466,False,Product
923,Irene,NaN,1991-02-28,10:23:00,135369,4.380,False,Business Development
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal

In [ ]:
import datetime as dt

# dt.time(8,30) de la manana
# dt.time(12,0) del mediodia


employees[employees['Last Login Time'].between(dt.time(8,30), dt.time(12,0))]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
...,...,...,...,...,...,...,...,...
977,Sarah,Female,1995-12-04,09:16:00,124566,5.949,False,Product
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
983,John,Male,1982-12-23,10:35:00,146907,11.738,False,Engineering
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance

In [ ]:
# The duplicated Method: identificar las filas duplicadas en un DF mediante el metodo duplicado
# todas las filas de employees donde el valor en la columna 'First Name' aparece más de una vez, excluyendo la primera vez que aparece cada nombre duplicado.
employees[employees['First Name'].duplicated()]
employees[employees['First Name'].duplicated(keep='first')]
employees[employees['First Name'].duplicated(keep='last')]
# ~ revierte los booleanos
# significa que los eventos ocurren una vez en el conjunto de datos original.
employees[~employees['First Name'].duplicated(keep=False)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
190,Carol,Female,1996-03-19,03:39:00,57783,9.129,False,Finance
291,Tammy,Female,1984-11-11,10:30:00,132839,17.463,True,Client Services
495,Eugene,Male,1984-05-24,10:54:00,81077,2.117,False,Sales
688,Brian,Male,2007-04-07,10:47:00,93901,17.821,True,Legal
832,Keith,Male,2003-02-12,03:02:00,120672,19.467,False,Legal
887,David,Male,2009-12-05,08:48:00,92242,15.407,False,Legal

In [21]:
# The drop_duplicates Method

employees.drop_duplicates()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [24]:
# The drop_duplicates Method

employees.drop_duplicates("Team",keep='last')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
951,NaN,Female,2010-09-14,05:19:00,143638,9.662,True,NaN
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
990,Robin,Female,1987-07-24,01:35:00,100765,10.982,True,Client Services
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [26]:
employees.drop_duplicates("Team",keep=False)

Empty DataFrame
Columns: [First Name, Gender, Start Date, Last Login Time, Salary, Bonus %, Senior Management, Team]
Index: []

In [28]:
employees.drop_duplicates(['Senior Management', 'Team']).sort_values('Team')

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
60,Paula,NaN,2005-11-23,02:01:00,48866,4.271,False,Distribution
40,Michael,Male,2008-10-10,11:25:00,99283,2.665,True,Distribution
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
54,Sara,Female,2007-08-15,09:23:00,83677,8.999,False,Engineering
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
16,Jeremy,Male,2010-09-21,05:56:00,90370,7.369,False,Human Resources
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
21,Matthew,Male,1995-09-05,02:12:00,100612,13.645,False,Marketing
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
45,Roger,Male,1980-04-17,11:32:00,88010,13.886,True,Sales
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
91,James,NaN,2005-01-26,11:00:00,128771,8.309,False,NaN

In [ ]:
# The unique and nunique methods

# encontrar valores unicos y contarlos en columnas de un DF 

employees['Gender'].unique()

employees['Team'].unique()

employees['Team'].nunique()

employees['Gender'].nunique()

employees['Team'].nunique(dropna=False)

employees.nunique()

#True borra los NaN
#False borra los NaN
employees.nunique(dropna=True)

First Name           200
Gender                 2
Start Date           972
Last Login Time      542
Salary               995
Bonus %              971
Senior Management      2
Team                  10
dtype: int64