In [172]:
import pandas as pd
import datetime as dt

In [173]:
someday = dt.date(2025,12,15)

someday.year
someday.month
someday.day

15

In [174]:
dt.datetime(2025, 12, 15)
dt.datetime(2025, 12, 15, 8)
dt.datetime(2025, 12, 15, 8, 13)
dt.datetime(2025, 12, 15, 8, 13, 59)

sometime = dt.datetime(2025, 12, 15, 8, 13, 59)
sometime

datetime.datetime(2025, 12, 15, 8, 13, 59)

In [175]:
pd.Timestamp(2025, 12, 15, 8, 13, 59)
pd.Timestamp(dt.date(2025, 12, 15))

Timestamp('2025-12-15 00:00:00')

In [176]:
pd.Timestamp("2025-01-01")

Timestamp('2025-01-01 00:00:00')

In [177]:
pd.Timestamp("2025/01/01")

Timestamp('2025-01-01 00:00:00')

In [178]:
pd.Timestamp("2025-01-01 08:35:21")

Timestamp('2025-01-01 08:35:21')

In [179]:
# Crea un objeto Timestamp de Pandas. Un Timestamp representa un punto específico en el tiempo. 
# La cadena "2025-01-01 08:35:21" se interpreta como una fecha y hora.

pd.Series([pd.Timestamp("2025-01-01 08:35:21")]).iloc[0]

Timestamp('2025-01-01 08:35:21')

In [180]:
pd.DatetimeIndex(["2025-01-01", "2025-02-01", "2025-03-01"])
index = pd.DatetimeIndex([
    dt.date(2026,1,10),
    dt.date(2026,2,20)
])

index[0]
type(index[0])

pandas._libs.tslibs.timestamps.Timestamp

In [181]:
pd.date_range(start="2025-01-01", end="2025-01-07")

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')

In [182]:
pd.date_range(start="2025-01-01", end="2025-01-07", freq="D")

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')

In [183]:
# "D" significa que la frecuencia es diaria
#"90D" significa que la frecuancia con saltos dependiendo el numero
pd.date_range(start="2025-01-01", end="2025-10-01", freq="90D")

DatetimeIndex(['2025-01-01', '2025-04-01', '2025-06-30', '2025-09-28'], dtype='datetime64[ns]', freq='90D')

In [184]:
pd.date_range(start="2025-01-01", end="2025-01-09", freq="B") # business days - Monday Friday

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-06',
               '2025-01-07', '2025-01-08', '2025-01-09'],
              dtype='datetime64[ns]', freq='B')

In [185]:
pd.date_range(start="2025-01-01", end="2025-02-28", freq="W") # saltos semanales

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09', '2025-02-16', '2025-02-23'],
              dtype='datetime64[ns]', freq='W-SUN')

In [186]:
pd.date_range(start="2025-01-01", end="2029-10-01", freq="2Y")

DatetimeIndex(['2025-12-31', '2027-12-31'], dtype='datetime64[ns]', freq='2A-DEC')

In [187]:
pd.date_range(start="2025-01-01", end="2025-10-01", freq="W-FRI")

DatetimeIndex(['2025-01-03', '2025-01-10', '2025-01-17', '2025-01-24',
               '2025-01-31', '2025-02-07', '2025-02-14', '2025-02-21',
               '2025-02-28', '2025-03-07', '2025-03-14', '2025-03-21',
               '2025-03-28', '2025-04-04', '2025-04-11', '2025-04-18',
               '2025-04-25', '2025-05-02', '2025-05-09', '2025-05-16',
               '2025-05-23', '2025-05-30', '2025-06-06', '2025-06-13',
               '2025-06-20', '2025-06-27', '2025-07-04', '2025-07-11',
               '2025-07-18', '2025-07-25', '2025-08-01', '2025-08-08',
               '2025-08-15', '2025-08-22', '2025-08-29', '2025-09-05',
               '2025-09-12', '2025-09-19', '2025-09-26'],
              dtype='datetime64[ns]', freq='W-FRI')

In [188]:
pd.date_range(start="2025-01-01", end="2025-10-01", freq="W-THU")

DatetimeIndex(['2025-01-02', '2025-01-09', '2025-01-16', '2025-01-23',
               '2025-01-30', '2025-02-06', '2025-02-13', '2025-02-20',
               '2025-02-27', '2025-03-06', '2025-03-13', '2025-03-20',
               '2025-03-27', '2025-04-03', '2025-04-10', '2025-04-17',
               '2025-04-24', '2025-05-01', '2025-05-08', '2025-05-15',
               '2025-05-22', '2025-05-29', '2025-06-05', '2025-06-12',
               '2025-06-19', '2025-06-26', '2025-07-03', '2025-07-10',
               '2025-07-17', '2025-07-24', '2025-07-31', '2025-08-07',
               '2025-08-14', '2025-08-21', '2025-08-28', '2025-09-04',
               '2025-09-11', '2025-09-18', '2025-09-25'],
              dtype='datetime64[ns]', freq='W-THU')

In [189]:
pd.date_range(start="2025-01-01", end="2025-01-07", freq="6H")

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 06:00:00',
               '2025-01-01 12:00:00', '2025-01-01 18:00:00',
               '2025-01-02 00:00:00', '2025-01-02 06:00:00',
               '2025-01-02 12:00:00', '2025-01-02 18:00:00',
               '2025-01-03 00:00:00', '2025-01-03 06:00:00',
               '2025-01-03 12:00:00', '2025-01-03 18:00:00',
               '2025-01-04 00:00:00', '2025-01-04 06:00:00',
               '2025-01-04 12:00:00', '2025-01-04 18:00:00',
               '2025-01-05 00:00:00', '2025-01-05 06:00:00',
               '2025-01-05 12:00:00', '2025-01-05 18:00:00',
               '2025-01-06 00:00:00', '2025-01-06 06:00:00',
               '2025-01-06 12:00:00', '2025-01-06 18:00:00',
               '2025-01-07 00:00:00'],
              dtype='datetime64[ns]', freq='6H')

In [190]:
pd.date_range(start="2025-01-01", end="2025-10-01", freq="M")

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30'],
              dtype='datetime64[ns]', freq='M')

In [191]:
# Inicio del mes
pd.date_range(start="2025-01-01", end="2025-10-01", freq="MS")

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01',
               '2025-09-01', '2025-10-01'],
              dtype='datetime64[ns]', freq='MS')

In [192]:
pd.date_range(start="2025-01-01", freq="D", periods=25)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12',
               '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16',
               '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20',
               '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24',
               '2025-01-25'],
              dtype='datetime64[ns]', freq='D')

In [193]:

pd.date_range(start="2025-01-01", freq="B", periods=180)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-06',
               '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10',
               '2025-01-13', '2025-01-14',
               ...
               '2025-08-27', '2025-08-28', '2025-08-29', '2025-09-01',
               '2025-09-02', '2025-09-03', '2025-09-04', '2025-09-05',
               '2025-09-08', '2025-09-09'],
              dtype='datetime64[ns]', length=180, freq='B')

In [194]:
import pandas as pd

date_range = pd.date_range(start="2025-01-01", freq="B", periods=180)

# Convertir el DatetimeIndex a un DataFrame
df = pd.DataFrame({'Fecha': date_range})

df

         Fecha
0   2025-01-01
1   2025-01-02
2   2025-01-03
3   2025-01-06
4   2025-01-07
..         ...
175 2025-09-03
176 2025-09-04
177 2025-09-05
178 2025-09-08
179 2025-09-09

[180 rows x 1 columns]

In [195]:
pd.date_range(end="2025-01-01", freq="B", periods=180)

DatetimeIndex(['2024-04-25', '2024-04-26', '2024-04-29', '2024-04-30',
               '2024-05-01', '2024-05-02', '2024-05-03', '2024-05-06',
               '2024-05-07', '2024-05-08',
               ...
               '2024-12-19', '2024-12-20', '2024-12-23', '2024-12-24',
               '2024-12-25', '2024-12-26', '2024-12-27', '2024-12-30',
               '2024-12-31', '2025-01-01'],
              dtype='datetime64[ns]', length=180, freq='B')

In [196]:
import pandas as pd

In [197]:
brunch_of_dates = pd.Series(pd.date_range(start= "2000-01-01", end="2020-12-31", freq="24H 3H"))

In [198]:
brunch_of_dates.dt

In [199]:
brunch_of_dates.head()

0   2000-01-01 00:00:00
1   2000-01-02 03:00:00
2   2000-01-03 06:00:00
3   2000-01-04 09:00:00
4   2000-01-05 12:00:00
dtype: datetime64[ns]

In [200]:
brunch_of_dates.dt.day

0        1
1        2
2        3
3        4
4        5
        ..
6813    25
6814    26
6815    27
6816    29
6817    30
Length: 6818, dtype: int32

In [201]:
brunch_of_dates = pd.Series(pd.date_range(start="2000-01-01", end="2020-12-31", freq="24D 3H"))

# Es un objeto especial de propiedades datetime y esta 
brunch_of_dates.dt

In [202]:
brunch_of_dates.dt.day
brunch_of_dates.dt.month
brunch_of_dates.dt.year
brunch_of_dates.dt.hour
# que dia del anio es
brunch_of_dates.dt.day_of_year
# Dia de la semana
brunch_of_dates.dt.day_name()
#
brunch_of_dates.dt.day_of_week

# booleans

brunch_of_dates.dt.is_month_end
brunch_of_dates.dt.is_month_start

# Los dias dentro de la serie que caen al principio de un trimestre
brunch_of_dates[brunch_of_dates.dt.is_quarter_start]

0     2000-01-01 00:00:00
106   2007-01-01 06:00:00
212   2014-01-01 12:00:00
299   2019-10-01 09:00:00
dtype: datetime64[ns]

In [203]:
stocks = pd.read_csv("IBM.csv", parse_dates=["Date"], index_col="Date", date_format="%d-%m-%Y").sort_index()
stocks.head()
stocks.tail()

                 Close        High         Low        Open   Volume
Date
31/12/2018   81.634117   82.122469   80.736406   81.389938  5212009
31/12/2019  100.880257  100.940474   99.645976   99.743816  3951265
31/12/2020   99.707405   99.826216   98.210367   98.392547  3738822
31/12/2021  116.311516  117.468889  116.268003  116.607382  3362100
31/12/2024  218.375153  219.587080  216.994352  219.259262  2270200

In [204]:
stocks.iloc[300]

Close     4.365355e+01
High      4.387330e+01
Low       4.335007e+01
Open      4.342856e+01
Volume    3.832858e+06
Name: 01/08/2005, dtype: float64

In [205]:
stocks.index = pd.to_datetime(stocks.index, format='%d/%m/%Y') # Ajusta el formato si es diferente
print(stocks.index)
stocks.loc["2021/12/31"]

DatetimeIndex(['1962-02-01', '1963-02-01', '1965-02-01', '1966-02-01',
               '1967-02-01', '1968-02-01', '1971-02-01', '1972-02-01',
               '1973-02-01', '1974-02-01',
               ...
               '2010-12-31', '2012-12-31', '2013-12-31', '2014-12-31',
               '2015-12-31', '2018-12-31', '2019-12-31', '2020-12-31',
               '2021-12-31', '2024-12-31'],
              dtype='datetime64[ns]', name='Date', length=15931, freq=None)

Close     1.163115e+02
High      1.174689e+02
Low       1.162680e+02
Open      1.166074e+02
Volume    3.362100e+06
Name: 2021-12-31 00:00:00, dtype: float64

In [206]:
stocks.loc["31/12/2021"]

Close     1.163115e+02
High      1.174689e+02
Low       1.162680e+02
Open      1.166074e+02
Volume    3.362100e+06
Name: 2021-12-31 00:00:00, dtype: float64

In [207]:
print(stocks.index)

DatetimeIndex(['1962-02-01', '1963-02-01', '1965-02-01', '1966-02-01',
               '1967-02-01', '1968-02-01', '1971-02-01', '1972-02-01',
               '1973-02-01', '1974-02-01',
               ...
               '2010-12-31', '2012-12-31', '2013-12-31', '2014-12-31',
               '2015-12-31', '2018-12-31', '2019-12-31', '2020-12-31',
               '2021-12-31', '2024-12-31'],
              dtype='datetime64[ns]', name='Date', length=15931, freq=None)

In [208]:
stocks.head()

               Close      High       Low      Open  Volume
Date
1962-02-01  1.445917  1.449828  1.427663  1.427663  674670
1963-02-01  1.105747  1.108683  1.103790  1.105747  564840
1965-02-01  1.456033  1.462570  1.454399  1.462570  546012
1966-02-01  1.610010  1.626372  1.610010  1.623099  476976
1967-02-01  1.931456  1.936371  1.919170  1.936371  435136

In [209]:
stocks.loc[pd.Timestamp(2021,12,31)]

Close     1.163115e+02
High      1.174689e+02
Low       1.162680e+02
Open      1.166074e+02
Volume    3.362100e+06
Name: 2021-12-31 00:00:00, dtype: float64

In [210]:
stocks = stocks.sort_index()
stocks_seleccionado = stocks.loc["03/04/2014":"12/12/2016"]
stocks_seleccionado

                 Close        High         Low        Open   Volume
Date
2014-03-04  112.923592  113.359685  112.463272  112.542011  4950718
2014-03-05  113.347572  113.838169  112.899366  113.002330  3645519
2014-03-06  113.650444  114.104712  113.202247  113.486915  3992896
2014-03-07  113.674652  114.425701  113.371810  114.080459  4307219
2014-03-10  112.893356  114.092612  112.566288  113.595954  4802395
...                ...         ...         ...         ...      ...
2016-12-06  106.061020  106.352054  105.121778  105.915503  2990514
2016-12-07  108.997810  109.255770  106.087501  106.226409  4639115
2016-12-08  109.374786  109.798110  108.620756  109.050688  3416654
2016-12-09  110.142090  110.274368  108.872130  109.255760  3291657
2016-12-12  109.467407  110.320652  109.182982  110.274349  3548346

[702 rows x 5 columns]

In [211]:
stocks.loc[pd.Timestamp(2014,6,1):pd.Timestamp(2016,12,31)]

                 Close        High         Low        Open   Volume
Date
2014-06-02  113.124153  113.483589  112.502759  112.557590  3347723
2014-06-03  112.320000  113.166802  112.167702  113.038871  2632887
2014-06-04  112.405312  112.977962  112.216454  112.527156  2486133
2014-06-05  113.300850  113.367864  112.045878  112.496695  2983401
2014-06-06  113.538422  114.318210  113.252096  113.599339  3448348
...                ...         ...         ...         ...      ...
2016-12-23  110.267723  110.783641  110.095750  110.459543  1779455
2016-12-27  110.552177  111.107779  110.360358  110.446344  1461785
2016-12-28  109.923843  110.949072  109.798173  110.651418  1838345
2016-12-29  110.194969  110.452928  109.798112  109.811340  1740021
2016-12-30  109.791519  110.261135  109.467421  110.089162  3088629

[653 rows x 5 columns]

In [212]:
stocks.truncate("03/04/2014","12/12/2016")

                 Close        High         Low        Open   Volume
Date
2014-03-04  112.923592  113.359685  112.463272  112.542011  4950718
2014-03-05  113.347572  113.838169  112.899366  113.002330  3645519
2014-03-06  113.650444  114.104712  113.202247  113.486915  3992896
2014-03-07  113.674652  114.425701  113.371810  114.080459  4307219
2014-03-10  112.893356  114.092612  112.566288  113.595954  4802395
...                ...         ...         ...         ...      ...
2016-12-06  106.061020  106.352054  105.121778  105.915503  2990514
2016-12-07  108.997810  109.255770  106.087501  106.226409  4639115
2016-12-08  109.374786  109.798110  108.620756  109.050688  3416654
2016-12-09  110.142090  110.274368  108.872130  109.255760  3291657
2016-12-12  109.467407  110.320652  109.182982  110.274349  3548346

[702 rows x 5 columns]

In [213]:
stocks.loc["03/04/2014","Close"]

112.9235916

In [214]:
stocks.loc["01/02/2013", "Close":"Low"]

Close    116.026077
High     116.026077
Low      114.519250
Name: 2013-01-02 00:00:00, dtype: float64

In [215]:
stocks.loc[pd.Timestamp(2014,6,1):pd.Timestamp(2016,12,31), "Close":"Volume"]

                 Close        High         Low        Open   Volume
Date
2014-06-02  113.124153  113.483589  112.502759  112.557590  3347723
2014-06-03  112.320000  113.166802  112.167702  113.038871  2632887
2014-06-04  112.405312  112.977962  112.216454  112.527156  2486133
2014-06-05  113.300850  113.367864  112.045878  112.496695  2983401
2014-06-06  113.538422  114.318210  113.252096  113.599339  3448348
...                ...         ...         ...         ...      ...
2016-12-23  110.267723  110.783641  110.095750  110.459543  1779455
2016-12-27  110.552177  111.107779  110.360358  110.446344  1461785
2016-12-28  109.923843  110.949072  109.798173  110.651418  1838345
2016-12-29  110.194969  110.452928  109.798112  109.811340  1740021
2016-12-30  109.791519  110.261135  109.467421  110.089162  3088629

[653 rows x 5 columns]

In [216]:
stocks.index

DatetimeIndex(['1962-01-02', '1962-01-03', '1962-01-04', '1962-01-05',
               '1962-01-08', '1962-01-09', '1962-01-10', '1962-01-11',
               '1962-01-12', '1962-01-15',
               ...
               '2025-04-04', '2025-04-07', '2025-04-08', '2025-04-09',
               '2025-04-10', '2025-04-11', '2025-04-14', '2025-04-15',
               '2025-04-16', '2025-04-17'],
              dtype='datetime64[ns]', name='Date', length=15931, freq=None)

In [220]:
# En resumen, stocks.index - pd.DateOffset(days=5) es una herramienta flexible para manipular y 
# analizar datos de series de tiempo, permitiéndote crear referencias temporales pasadas para 
# comparaciones, generar rangos de fechas desplazados y realizar alineaciones basadas en desfases de tiempo. 
# La aplicación específica dependerá del contexto de tu análisis
stocks.index + pd.DateOffset(days=5)
stocks.index - pd.DateOffset(days=5)
stocks.index - pd.DateOffset(months=5)
stocks.index - pd.DateOffset(years=1)
stocks.index - pd.DateOffset(hours=7)
stocks.index + pd.DateOffset(years =1, months=3, days=2, hours=14, minutes=23, seconds=12)

DatetimeIndex(['1963-04-04 14:23:12', '1963-04-05 14:23:12',
               '1963-04-06 14:23:12', '1963-04-07 14:23:12',
               '1963-04-10 14:23:12', '1963-04-11 14:23:12',
               '1963-04-12 14:23:12', '1963-04-13 14:23:12',
               '1963-04-14 14:23:12', '1963-04-17 14:23:12',
               ...
               '2026-07-06 14:23:12', '2026-07-09 14:23:12',
               '2026-07-10 14:23:12', '2026-07-11 14:23:12',
               '2026-07-12 14:23:12', '2026-07-13 14:23:12',
               '2026-07-16 14:23:12', '2026-07-17 14:23:12',
               '2026-07-18 14:23:12', '2026-07-19 14:23:12'],
              dtype='datetime64[ns]', name='Date', length=15931, freq=None)

In [228]:
birthdays = pd.date_range(start="2000-12-12", end="2023-04-12", freq=pd.DateOffset(years=1))
birthdays

DatetimeIndex(['2000-12-12', '2001-12-12', '2002-12-12', '2003-12-12',
               '2004-12-12', '2005-12-12', '2006-12-12', '2007-12-12',
               '2008-12-12', '2009-12-12', '2010-12-12', '2011-12-12',
               '2012-12-12', '2013-12-12', '2014-12-12', '2015-12-12',
               '2016-12-12', '2017-12-12', '2018-12-12', '2019-12-12',
               '2020-12-12', '2021-12-12', '2022-12-12'],
              dtype='datetime64[ns]', freq='<DateOffset: years=1>')

In [231]:
stocks[stocks.index.isin(birthdays)]

                 Close        High         Low        Open    Volume
Date
2000-12-12   47.568562   48.708688   46.871819   48.265308   8277312
2001-12-12   62.734787   62.739879   61.135863   61.675629   8344883
2002-12-12   41.123787   41.903482   40.882700   41.677783   7540300
2003-12-12   47.918526   48.151113   47.675598   47.913357   5313471
2005-12-12   45.193615   45.924410   45.088463   45.745653   6322129
2006-12-12   50.148125   50.537078   49.711218   49.871064   8141855
2007-12-12   58.606693   59.541420   58.017765   58.984908   8242271
2008-12-12   45.190537   45.597362   42.914519   43.255373  10859258
2011-12-12  111.681809  112.681357  111.123920  112.530263   3970721
2012-12-12  114.016930  115.080575  113.727376  114.991939   4437027
2013-12-12  104.434799  105.898585  104.392630  105.452822   5932494
2014-12-12   95.870529   99.029604   95.839676   98.875357   9007838
2016-12-12  109.467407  110.320652  109.182982  110.274349   3548346
2017-12-12  107.694367  108.457037  106.608767  108.079145   6612603
2018-12-12   87.013199   88.248445   86.898293   87.982722   3724283
2019-12-12  101.843582  102.099479  100.594251  100.624353   5046009
2022-12-12  136.282745  136.282745  134.209410  135.013173   4032800

In [163]:
fecha_referencia = pd.to_datetime('2014-03-10')
indice_desplazado = stocks.index - pd.DateOffset(days=5)
# Esto devolverá True para las fechas en stocks.index que, al restar 5 días, son iguales a la fecha de referencia
mascara = indice_desplazado == fecha_referencia
datos_desplazados = stocks[mascara]

In [ ]:
serie_A = pd.Series(range(len(stocks)), index=stocks.index)
serie_B_alineada = pd.Series(range(len(stocks)), index=stocks.index - pd.DateOffset(days=5))

# Ahora podrías intentar alinear serie_A con los valores de serie_B que ocurrieron 5 días antes
df_comparacion = pd.DataFrame({'A': serie_A, 'B_retrasada': serie_B_alineada}).reindex(stocks.index)
df_comparacion

In [ ]:
stocks = pd.read_csv("IBM.csv", parse_dates=["Date"], index_col="Date", date_format="%d-%m-%Y").sort_index()
stocks.head()
stocks.tail()

In [242]:
stocks.index + pd.tseries.offsets.MonthEnd()

stocks.index + pd.tseries.offsets.QuarterEnd()
stocks.index - pd.tseries.offsets.QuarterEnd()

stocks.index + pd.tseries.offsets.QuarterBegin(startingMonth=1)
stocks.index - pd.tseries.offsets.QuarterBegin(startingMonth=1)

stocks.index + pd.tseries.offsets.YearEnd()
stocks.index + pd.tseries.offsets.YearBegin()

DatetimeIndex(['1963-01-01', '1963-01-01', '1963-01-01', '1963-01-01',
               '1963-01-01', '1963-01-01', '1963-01-01', '1963-01-01',
               '1963-01-01', '1963-01-01',
               ...
               '2026-01-01', '2026-01-01', '2026-01-01', '2026-01-01',
               '2026-01-01', '2026-01-01', '2026-01-01', '2026-01-01',
               '2026-01-01', '2026-01-01'],
              dtype='datetime64[ns]', name='Date', length=15931, freq=None)

In [ ]:
#TIMEDELTAS

In [243]:
pd.Timestamp("2023-03-31 12:30:48") - pd.Timestamp("2023-03-20 19:25:39")

Timedelta('10 days 17:05:09')

In [248]:
pd.Timedelta(days=3, hours=2, minutes=5)
pd.Timedelta("5 minutes")
pd.Timedelta("3 days 2 hours 5 minutes")

Timedelta('3 days 02:05:00')

In [259]:
dates = pd.read_csv("ecommerce.csv", parse_dates=["order_date", "delivery_date"]).set_index("ID")

dates

C:\Users\johan\AppData\Local\Temp\ipykernel_18888\2167069660.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dates = pd.read_csv("ecommerce.csv", parse_dates=["order_date", "delivery_date"]).set_index("ID")
C:\Users\johan\AppData\Local\Temp\ipykernel_18888\2167069660.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dates = pd.read_csv("ecommerce.csv", parse_dates=["order_date", "delivery_date"]).set_index("ID")

    order_date delivery_date
ID
1   1998-05-24    1999-02-05
2   1992-04-22    1998-03-06
4   1991-02-10    1992-08-26
5   1992-07-21    1997-11-20
7   1993-09-02    1998-06-10
..         ...           ...
990 1991-06-24    1996-02-02
991 1991-09-09    1998-03-30
993 1990-11-16    1998-04-27
994 1993-06-03    1993-06-13
997 1990-01-04    1991-10-03

[501 rows x 2 columns]

In [261]:
dates["Delivery Time"] = dates["delivery_date"] - dates["order_date"]

In [262]:
dates.head()

   order_date delivery_date Delivery Time
ID
1  1998-05-24    1999-02-05      257 days
2  1992-04-22    1998-03-06     2144 days
4  1991-02-10    1992-08-26      563 days
5  1992-07-21    1997-11-20     1948 days
7  1993-09-02    1998-06-10     1742 days

In [265]:
# fechas futuras

dates["If it took twice as long"] = dates["delivery_date"] + dates["Delivery Time"]

dates.head()

   order_date delivery_date Delivery Time If it took twice as long
ID
1  1998-05-24    1999-02-05      257 days               1999-10-20
2  1992-04-22    1998-03-06     2144 days               2004-01-18
4  1991-02-10    1992-08-26      563 days               1994-03-12
5  1992-07-21    1997-11-20     1948 days               2003-03-22
7  1993-09-02    1998-06-10     1742 days               2003-03-18

In [ ]:
dates["Delivery Time"].max()
dates["Delivery Time"].min()
dates["Delivery Time"].mean()

Timedelta('1217 days 22:53:53.532934128')