In [105]:
import pandas as pd
big_mac = pd.read_csv("big-mac-source-data.csv",parse_dates=["date"], date_format="%Y-%m-%d")
big_mac.head()

,name,iso_a3,currency_code,local_price,dollar_ex,GDP_dollar,date
0,Argentina,ARG,ARS,2.50,1.000000,NaN,2000-04-01
1,Australia,AUS,AUD,2.59,1.680000,NaN,2000-04-01
2,Brazil,BRA,BRL,2.95,1.790000,NaN,2000-04-01
3,Britain,GBR,GBP,1.90,0.632911,NaN,2000-04-01
4,Canada,CAN,CAD,2.85,1.470000,NaN,2000-04-01

In [98]:
big_mac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1948 entries, 0 to 1947
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           1948 non-null   object
 1   iso_a3         1948 non-null   object
 2   currency_code  1948 non-null   object
 3   local_price    1948 non-null   float64
 4   dollar_ex      1948 non-null   float64
 5   GDP_dollar     1335 non-null   float64
 6   date           1948 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(3)
memory usage: 106.7+ KB

In [ ]:
# borra temporalmente
# big_mac.drop(columns=["iso_a3","currency_code","dollar_ex","GDP_dollar"])
# bond = bond.rename(columns={"Year": "Year of Release", "Box Office":"Revenue"})
import pandas as pd
big_mac = pd.read_csv("big-mac-source-data.csv",parse_dates=["date"], date_format="%Y-%m-%d")
big_mac.head()

del big_mac ["iso_a3"]
del big_mac ["currency_code"]
del big_mac ["dollar_ex"]
del big_mac ["GDP_dollar"]

big_mac = big_mac.rename(columns={"name":"Country","date":"Date","local_price":"Price in US Dollars"})
big_mac

In [107]:
big_mac = big_mac.rename(columns={"name":"Country","date":"Date","local_price":"Price in US Dollars"})
big_mac

            Country  Price in US Dollars       Date
0         Argentina                 2.50 2000-04-01
1         Australia                 2.59 2000-04-01
2            Brazil                 2.95 2000-04-01
3           Britain                 1.90 2000-04-01
4            Canada                 2.85 2000-04-01
...             ...                  ...        ...
1943        Uruguay               255.00 2022-07-01
1944  United States                 5.77 2022-07-01
1945      Venezuela                10.00 2022-07-01
1946        Vietnam             69000.00 2022-07-01
1947   South Africa                39.90 2022-07-01

[1948 rows x 3 columns]

In [73]:
big_mac.dtypes

Country                        object
Price in US Dollars           float64
Date                   datetime64[ns]
dtype: object

In [74]:
big_mac.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1948 entries, 0 to 1947
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country              1948 non-null   object
 1   Price in US Dollars  1948 non-null   float64
 2   Date                 1948 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 45.8+ KB

In [75]:
# Create a MultiIndex

big_mac.copy()

            Country  Price in US Dollars       Date
0         Argentina                 2.50 2000-04-01
1         Australia                 2.59 2000-04-01
2            Brazil                 2.95 2000-04-01
3           Britain                 1.90 2000-04-01
4            Canada                 2.85 2000-04-01
...             ...                  ...        ...
1943        Uruguay               255.00 2022-07-01
1944  United States                 5.77 2022-07-01
1945      Venezuela                10.00 2022-07-01
1946        Vietnam             69000.00 2022-07-01
1947   South Africa                39.90 2022-07-01

[1948 rows x 3 columns]

In [76]:
big_mac.head()

     Country  Price in US Dollars       Date
0  Argentina                 2.50 2000-04-01
1  Australia                 2.59 2000-04-01
2     Brazil                 2.95 2000-04-01
3    Britain                 1.90 2000-04-01
4     Canada                 2.85 2000-04-01

In [108]:
big_mac = big_mac.set_index(keys=["Date","Country"])

In [94]:
print(big_mac.columns)

Index(['Price in US Dollars'], dtype='object')

In [ ]:
big_mac = big_mac.set_index(keys=["Country", "Date"]).sort_index()

In [ ]:
big_mac.nunique()

big_mac.set_index(keys=["Date", "Country"])

In [109]:
big_mac.index.names

FrozenList(['Date', 'Country'])

In [110]:
big_mac.index[0]

(Timestamp('2000-04-01 00:00:00'), 'Argentina')

In [3]:
#Extract Index Level Values

import pandas as pd
big_mac = pd.read_csv("big-mac-source-data.csv",parse_dates=["date"], date_format="%Y-%m-%d", index_col=["date", "name"]).sort_index()
big_mac.head()

del big_mac ["iso_a3"]
del big_mac ["currency_code"]
del big_mac ["dollar_ex"]
del big_mac ["GDP_dollar"]

big_mac = big_mac.rename(columns={"name":"Country","date":"Date","local_price":"Price in US Dollars"})
big_mac

                                 Price in US Dollars
date       name
2000-04-01 Argentina                            2.50
           Australia                            2.59
           Brazil                               2.95
           Britain                              1.90
           Canada                               2.85
...                                              ...
2022-07-01 United Arab Emirates                18.00
           United States                        5.77
           Uruguay                            255.00
           Venezuela                           10.00
           Vietnam                          69000.00

[1948 rows x 1 columns]

In [9]:
big_mac.index.get_level_values("date")
big_mac.index.get_level_values(0)



big_mac.index.get_level_values("name")
big_mac.index.get_level_values(1)

Index(['Argentina', 'Australia', 'Brazil', 'Britain', 'Canada', 'Chile',
       'China', 'Czech Republic', 'Denmark', 'Euro area',
       ...
       'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'Ukraine',
       'United Arab Emirates', 'United States', 'Uruguay', 'Venezuela',
       'Vietnam'],
      dtype='object', name='name', length=1948)

In [10]:
# Rename Index Levels

big_mac.index

MultiIndex([('2000-04-01',            'Argentina'),
            ('2000-04-01',            'Australia'),
            ('2000-04-01',               'Brazil'),
            ('2000-04-01',              'Britain'),
            ('2000-04-01',               'Canada'),
            ('2000-04-01',                'Chile'),
            ('2000-04-01',                'China'),
            ('2000-04-01',       'Czech Republic'),
            ('2000-04-01',              'Denmark'),
            ('2000-04-01',            'Euro area'),
            ...
            ('2022-07-01',          'Switzerland'),
            ('2022-07-01',               'Taiwan'),
            ('2022-07-01',             'Thailand'),
            ('2022-07-01',               'Turkey'),
            ('2022-07-01',              'Ukraine'),
            ('2022-07-01', 'United Arab Emirates'),
            ('2022-07-01',        'United States'),
            ('2022-07-01',              'Uruguay'),
            ('2022-07-01',            'Venezuela'),
            ('2022-07-01',              'Vietnam')],
           names=['date', 'name'], length=1948)

In [15]:
big_mac.index.set_names(names="Time", level=0)
big_mac.index.set_names(names="name", level=1)

MultiIndex([('2000-04-01',            'Argentina'),
            ('2000-04-01',            'Australia'),
            ('2000-04-01',               'Brazil'),
            ('2000-04-01',              'Britain'),
            ('2000-04-01',               'Canada'),
            ('2000-04-01',                'Chile'),
            ('2000-04-01',                'China'),
            ('2000-04-01',       'Czech Republic'),
            ('2000-04-01',              'Denmark'),
            ('2000-04-01',            'Euro area'),
            ...
            ('2022-07-01',          'Switzerland'),
            ('2022-07-01',               'Taiwan'),
            ('2022-07-01',             'Thailand'),
            ('2022-07-01',               'Turkey'),
            ('2022-07-01',              'Ukraine'),
            ('2022-07-01', 'United Arab Emirates'),
            ('2022-07-01',        'United States'),
            ('2022-07-01',              'Uruguay'),
            ('2022-07-01',            'Venezuela'),
            ('2022-07-01',              'Vietnam')],
           names=['date', 'name'], length=1948)

In [17]:
# Su propósito es asignar nombres a las diferentes "capas" o "niveles" que pueda tener el índice.
big_mac.index.set_names(names=["Time","Location"])

MultiIndex([('2000-04-01',            'Argentina'),
            ('2000-04-01',            'Australia'),
            ('2000-04-01',               'Brazil'),
            ('2000-04-01',              'Britain'),
            ('2000-04-01',               'Canada'),
            ('2000-04-01',                'Chile'),
            ('2000-04-01',                'China'),
            ('2000-04-01',       'Czech Republic'),
            ('2000-04-01',              'Denmark'),
            ('2000-04-01',            'Euro area'),
            ...
            ('2022-07-01',          'Switzerland'),
            ('2022-07-01',               'Taiwan'),
            ('2022-07-01',             'Thailand'),
            ('2022-07-01',               'Turkey'),
            ('2022-07-01',              'Ukraine'),
            ('2022-07-01', 'United Arab Emirates'),
            ('2022-07-01',        'United States'),
            ('2022-07-01',              'Uruguay'),
            ('2022-07-01',            'Venezuela'),
            ('2022-07-01',              'Vietnam')],
           names=['Time', 'Location'], length=1948)

In [18]:
# Sort_index Method on a MultiIndex DataFrame
import pandas as pd
big_mac = pd.read_csv("big-mac-source-data.csv",parse_dates=["date"], date_format="%Y-%m-%d", index_col=["date", "name"]).sort_index()
big_mac.head()

                     iso_a3 currency_code  local_price  dollar_ex  GDP_dollar
date       name
2000-04-01 Argentina    ARG           ARS         2.50   1.000000         NaN
           Australia    AUS           AUD         2.59   1.680000         NaN
           Brazil       BRA           BRL         2.95   1.790000         NaN
           Britain      GBR           GBP         1.90   0.632911         NaN
           Canada       CAN           CAD         2.85   1.470000         NaN

In [19]:

del big_mac ["iso_a3"]
del big_mac ["currency_code"]
del big_mac ["dollar_ex"]
del big_mac ["GDP_dollar"]

In [21]:
big_mac = big_mac.rename(columns={"name":"Country","date":"Date","local_price":"Price in US Dollars"})
big_mac

                                 Price in US Dollars
date       name
2000-04-01 Argentina                            2.50
           Australia                            2.59
           Brazil                               2.95
           Britain                              1.90
           Canada                               2.85
...                                              ...
2022-07-01 United Arab Emirates                18.00
           United States                        5.77
           Uruguay                            255.00
           Venezuela                           10.00
           Vietnam                          69000.00

[1948 rows x 1 columns]

In [26]:
# Ordenar de menor a mayor
big_mac.sort_index()


big_mac.sort_index(ascending=False)

big_mac.sort_index(ascending=[True,False])

                          Price in US Dollars
date       name
2000-04-01 United States                 2.24
           Thailand                     55.00
           Taiwan                       70.00
           Switzerland                   5.90
           Sweden                       24.00
...                                       ...
2022-07-01 Bahrain                       1.60
           Azerbaijan                    4.70
           Austria                       4.35
           Australia                     6.70
           Argentina                   590.00

[1948 rows x 1 columns]

In [1]:
import pandas as pd
big_mac = pd.read_csv("big-mac-source-data.csv",parse_dates=["date"], date_format="%Y-%m-%d", index_col=["date", "name"]).sort_index()
big_mac.head()

del big_mac ["iso_a3"]
del big_mac ["currency_code"]
del big_mac ["dollar_ex"]
del big_mac ["GDP_dollar"]

big_mac = big_mac.rename(columns={"name":"Country","date":"Date","local_price":"Price in US Dollars"})
big_mac

                                 Price in US Dollars
date       name
2000-04-01 Argentina                            2.50
           Australia                            2.59
           Brazil                               2.95
           Britain                              1.90
           Canada                               2.85
...                                              ...
2022-07-01 United Arab Emirates                18.00
           United States                        5.77
           Uruguay                            255.00
           Venezuela                           10.00
           Vietnam                          69000.00

[1948 rows x 1 columns]

In [30]:
#Extract Rows from MI DF

1,

(1,)

In [31]:
1

1

In [32]:
# lista ([1,2])
# tupla ((1,2))

In [33]:
big_mac.iloc[2]

Price in US Dollars    2.95
Name: (2000-04-01 00:00:00, Brazil), dtype: float64

In [37]:
big_mac.loc["2000-04-01"]
big_mac.loc["2000-04-01", "Canada"]

Price in US Dollars    2.85
Name: (2000-04-01 00:00:00, Canada), dtype: float64

In [38]:
big_mac.loc["2000-04-01", "Price in US Dollars"]

name
Argentina             2.50
Australia             2.59
Brazil                2.95
Britain               1.90
Canada                2.85
Chile              1260.00
China                 9.90
Czech Republic       54.37
Denmark              24.75
Euro area             2.56
Hong Kong            10.20
Hungary             339.00
Indonesia         14500.00
Israel               14.50
Japan               294.00
Malaysia              4.52
Mexico               20.90
New Zealand           3.40
Poland                5.50
Russia               39.50
Singapore             3.20
South Africa          9.00
South Korea        3000.00
Sweden               24.00
Switzerland           5.90
Taiwan               70.00
Thailand             55.00
United States         2.24
Name: Price in US Dollars, dtype: float64

In [ ]:
big_mac.loc[("2000-04-01", "Canada")]

Price in US Dollars    2.85
Name: (2000-04-01 00:00:00, Canada), dtype: float64

In [40]:
big_mac.loc[("2000-04-01", "Hungary"):("2000-04-01", "Poland")]

                        Price in US Dollars
date       name
2000-04-01 Hungary                   339.00
           Indonesia               14500.00
           Israel                     14.50
           Japan                     294.00
           Malaysia                    4.52
           Mexico                     20.90
           New Zealand                 3.40
           Poland                      5.50

In [44]:
start = ("2000-04-01", "Hungary")
end = ("2000-04-01", "Poland")

big_mac.loc[start:end]

                        Price in US Dollars
date       name
2000-04-01 Hungary                   339.00
           Indonesia               14500.00
           Israel                     14.50
           Japan                     294.00
           Malaysia                    4.52
           Mexico                     20.90
           New Zealand                 3.40
           Poland                      5.50

In [45]:
big_mac.loc[("2000-04-01", "Hungary"):]

                                 Price in US Dollars
date       name
2000-04-01 Hungary                            339.00
           Indonesia                        14500.00
           Israel                              14.50
           Japan                              294.00
           Malaysia                             4.52
...                                              ...
2022-07-01 United Arab Emirates                18.00
           United States                        5.77
           Uruguay                            255.00
           Venezuela                           10.00
           Vietnam                          69000.00

[1937 rows x 1 columns]

In [46]:
big_mac.loc[("2000-04-01", "Brazil"):("2013-07-01","Turkey")]

                        Price in US Dollars
date       name
2000-04-01 Brazil                      2.95
           Britain                     1.90
           Canada                      2.85
           Chile                    1260.00
           China                       9.90
...                                     ...
2013-07-01 Sweden                     41.61
           Switzerland                 6.50
           Taiwan                     79.00
           Thailand                   89.00
           Turkey                      8.50

[786 rows x 1 columns]

In [ ]:
# Extraccion de filas despues de la coma

big_mac.loc[("2000-04-01", "Brazil"):("2013-07-01","Turkey"),"Price in US Dollars"]

date        name
2000-04-01  Brazil            2.95
            Britain           1.90
            Canada            2.85
            Chile          1260.00
            China             9.90
                            ...
2013-07-01  Sweden           41.61
            Switzerland       6.50
            Taiwan           79.00
            Thailand         89.00
            Turkey            8.50
Name: Price in US Dollars, Length: 786, dtype: float64

In [2]:
start = ("2018-01-01", "China")
end = ("2018-01-01","Denmark")

big_mac.loc[start:end].transpose()

date                2018-01-01
name                     China Colombia Costa Rica Czech Republic Denmark
Price in US Dollars       20.4  10900.0     2290.0           79.0    30.0

In [7]:
# The stack method
world = pd.read_csv("worldstats.csv", index_col=["year","country"]).sort_index()
world.head()

                   Population           GDP
year country
1960 Afghanistan    8994793.0  5.377778e+08
     Algeria       11124892.0  2.723638e+09
     Australia     10276477.0  1.856759e+10
     Austria        7047539.0  6.592694e+09
     Bahamas, The    109526.0  1.698023e+08

In [8]:
world.stack()

year  country
1960  Afghanistan  Population    8.994793e+06
                   GDP           5.377778e+08
      Algeria      Population    1.112489e+07
                   GDP           2.723638e+09
      Australia    Population    1.027648e+07
                                     ...
2015  World        GDP           7.343364e+13
      Zambia       Population    1.621177e+07
                   GDP           2.120156e+10
      Zimbabwe     Population    1.560275e+07
                   GDP           1.389294e+10
Length: 22422, dtype: float64

In [9]:
type(world.stack())

pandas.core.series.Series

In [11]:
world.stack().to_frame()

                                        0
year country
1960 Afghanistan Population  8.994793e+06
                 GDP         5.377778e+08
     Algeria     Population  1.112489e+07
                 GDP         2.723638e+09
     Australia   Population  1.027648e+07
...                                   ...
2015 World       GDP         7.343364e+13
     Zambia      Population  1.621177e+07
                 GDP         2.120156e+10
     Zimbabwe    Population  1.560275e+07
                 GDP         1.389294e+10

[22422 rows x 1 columns]

In [16]:
world.unstack()

         Population                                              \
country Afghanistan    Albania     Algeria  Andorra      Angola
year
1960      8994793.0        NaN  11124892.0      NaN         NaN
1961      9164945.0        NaN  11404859.0      NaN         NaN
1962      9343772.0        NaN  11690152.0      NaN         NaN
1963      9531555.0        NaN  11985130.0      NaN         NaN
1964      9728645.0        NaN  12295973.0      NaN         NaN
1965      9935358.0        NaN  12626953.0      NaN         NaN
1966     10148841.0        NaN  12980269.0      NaN         NaN
1967     10368600.0        NaN  13354197.0      NaN         NaN
1968     10599790.0        NaN  13744383.0      NaN         NaN
1969     10849510.0        NaN  14144437.0      NaN         NaN
1970     11121097.0        NaN  14550033.0  24279.0         NaN
1971     11412821.0        NaN  14960111.0  25560.0         NaN
1972     11716896.0        NaN  15377095.0  26892.0         NaN
1973     12022514.0        NaN  15804428.0  28231.0         NaN
1974     12315553.0        NaN  16247113.0  29514.0         NaN
1975     12582954.0        NaN  16709098.0  30706.0         NaN
1976     12831361.0        NaN  17190236.0  31781.0         NaN
1977     13056499.0        NaN  17690184.0  32769.0         NaN
1978     13222547.0        NaN  18212331.0  33746.0         NaN
1979     13283279.0        NaN  18760761.0  34819.0         NaN
1980     13211412.0        NaN  19337723.0  36063.0         NaN
1981     12996923.0        NaN  19943667.0  37502.0         NaN
1982            NaN        NaN  20575701.0  39112.0         NaN
1983            NaN        NaN  21228288.0  40862.0         NaN
1984            NaN  2904429.0  21893857.0  42704.0         NaN
1985            NaN  2964762.0  22565908.0  44597.0   9745209.0
1986            NaN  3022635.0  23241276.0  46515.0  10023700.0
1987            NaN  3083605.0  23917889.0  48458.0  10285712.0
1988            NaN  3142336.0  24591493.0  50431.0  10544904.0
1989            NaN  3227943.0  25257671.0  52449.0  10820992.0
1990            NaN  3286542.0  25912364.0  54511.0  11127870.0
1991            NaN  3266790.0  26554277.0  56674.0  11472173.0
1992            NaN  3247039.0  27180921.0  58904.0  11848971.0
1993            NaN  3227287.0  27785977.0  61003.0  12246786.0
1994            NaN  3207536.0  28362015.0  62707.0  12648483.0
1995            NaN  3187784.0  28904300.0  63854.0  13042666.0
1996            NaN  3168033.0  29411839.0  64291.0  13424813.0
1997            NaN  3148281.0  29887717.0  64147.0  13801868.0
1998            NaN  3128530.0  30336880.0  63888.0  14187710.0
1999            NaN  3108778.0  30766551.0  64161.0  14601983.0
2000            NaN  3089027.0  31183658.0  65399.0  15058638.0
2001     20531160.0  3060173.0  31590320.0  67770.0  15562791.0
2002     21487079.0  3051010.0  31990387.0  71046.0  16109696.0
2003     22507368.0  3039616.0  32394886.0  74783.0  16691395.0
2004     23499850.0  3026939.0  32817225.0  78337.0  17295500.0
2005     24399948.0  3011487.0  33267887.0  81223.0  17912942.0
2006     25183615.0  2992547.0  33749328.0  83373.0  18541467.0
2007     25877544.0  2970017.0  34261971.0  84878.0  19183907.0
2008     26528741.0  2947314.0  34811059.0  85616.0  19842251.0
2009     27207291.0  2927519.0  35401790.0  85474.0  20520103.0
2010     27962207.0  2913021.0  36036159.0  84419.0  21219954.0
2011     28809167.0  2904780.0  36717132.0  82326.0  21942296.0
2012     29726803.0  2900247.0  37439427.0  79316.0  22685632.0
2013     30682500.0  2896652.0  38186135.0  75902.0  23448202.0
2014     31627506.0  2893654.0  38934334.0      NaN  24227524.0
2015     32526562.0  2889167.0  39666519.0      NaN  25021974.0

                                                                           \
country Antigua and Barbuda   Arab World   Argentina    Armenia     Aruba
year
1960                    NaN          NaN         NaN        NaN       NaN
1961                    NaN          NaN         NaN        NaN       NaN
1962                    NaN          NaN  21287682.0        NaN       NaN
1963                    NaN          NaN  21621845.0        NaN       NaN
1964                    NaN          NaN  21953926.0        NaN       NaN
1965                    NaN          NaN  22283389.0        NaN       NaN
1966                    NaN          NaN  22608747.0        NaN       NaN
1967                    NaN          NaN  22932201.0        NaN       NaN
1968                    NaN  115557094.0  23261273.0        NaN       NaN
1969                    NaN  118823872.0  23605992.0        NaN       NaN
1970                    NaN  122128175.0  23973062.0        NaN       NaN
1971                    NaN  125439089.0  24366442.0        NaN       NaN
1972                    NaN  128801209.0  24782950.0        NaN       NaN
1973                    NaN  132298955.0  25213388.0        NaN       NaN
1974                    NaN  136044481.0  25644505.0        NaN       NaN
1975                    NaN  140114424.0  26066975.0        NaN       NaN
1976                    NaN  144542039.0  26477153.0        NaN       NaN
1977                70223.0  149296257.0  26878567.0        NaN       NaN
1978                70508.0  154303887.0  27277742.0        NaN       NaN
1979                70553.0  159455867.0  27684530.0        NaN       NaN
1980                70301.0  164670713.0  28105889.0        NaN       NaN
1981                69750.0  169926632.0  28543366.0        NaN       NaN
1982                68950.0  175237742.0  28993989.0        NaN       NaN
1983                67958.0  180606318.0  29454739.0        NaN       NaN
1984                66863.0  186005735.0  29920907.0        NaN       NaN
1985                65744.0  191564251.0  30388781.0        NaN       NaN
1986                64605.0  197202142.0  30857242.0        NaN       NaN
1987                63484.0  202851923.0  31326473.0        NaN       NaN
1988                62538.0  208546282.0  31795515.0        NaN       NaN
1989                61967.0  214250542.0  32263559.0        NaN       NaN
1990                61906.0  222117305.0  32729740.0  3544695.0       NaN
1991                62412.0  228171034.0  33193920.0  3511912.0       NaN
1992                63434.0  232417246.0  33655149.0  3449497.0       NaN
1993                64868.0  238628852.0  34110912.0  3369673.0       NaN
1994                66550.0  244893420.0  34558114.0  3289943.0   76700.0
1995                68349.0  252591048.0  34994818.0  3223173.0   80326.0
1996                70245.0  258423164.0  35419683.0  3173425.0   83195.0
1997                72232.0  264153948.0  35833965.0  3137652.0   85447.0
1998                74206.0  269795252.0  36241578.0  3112958.0   87276.0
1999                76041.0  275503565.0  36648054.0  3093820.0   89004.0
2000                77648.0  281326250.0  37057453.0  3076098.0   90858.0
2001                78972.0  287291826.0  37471535.0  3060036.0   92894.0
2002                80030.0  293402563.0  37889443.0  3047249.0   94995.0
2003                80904.0  299731956.0  38309475.0  3036420.0   97015.0
2004                81718.0  306387415.0  38728778.0  3025982.0   98742.0
2005                82565.0  313430911.0  39145491.0  3014917.0  100031.0
2006                83467.0  320906736.0  39558750.0  3002161.0  100830.0
2007                84397.0  328766559.0  39969903.0  2988117.0  101218.0
2008                85350.0  336886468.0  40381860.0  2975029.0  101342.0
2009                86300.0  345054176.0  40798641.0  2966108.0  101416.0
2010                87233.0  353112237.0  41222875.0  2963496.0  101597.0
2011                88152.0  361031820.0  41655616.0  2967984.0  101936.0
2012                89069.0  368802611.0  42095224.0  2978339.0       NaN
2013                89985.0  376504253.0  42538304.0  2992192.0       NaN
2014                90900.0  384222592.0  42980026.0  3006154.0       NaN
2015                91818.0  392022276.0         NaN  3017712.0       NaN

         ...           GDP                                            \
country  ...    Uzbekistan       Vanuatu Venezuela, RB       Vietnam
year     ...
1960     ...           NaN           NaN  8.607600e+09           NaN
1961     ...           NaN           NaN  8.923367e+09           NaN
1962     ...           NaN           NaN  9.873398e+09           NaN
1963     ...           NaN           NaN  1.066338e+10           NaN
1964     ...           NaN           NaN  9.113581e+09           NaN
1965     ...           NaN           NaN  9.602945e+09           NaN
1966     ...           NaN           NaN  1.009657e+10           NaN
1967     ...           NaN           NaN  1.047278e+10           NaN
1968     ...           NaN           NaN  1.147091e+10           NaN
1969     ...           NaN           NaN  1.192757e+10           NaN
1970     ...           NaN           NaN  1.299312e+10           NaN
1971     ...           NaN           NaN  1.447156e+10           NaN
1972     ...           NaN           NaN  1.592287e+10           NaN
1973     ...           NaN           NaN  1.944593e+10           NaN
1974     ...           NaN           NaN  2.908710e+10           NaN
1975     ...           NaN           NaN  3.141316e+10           NaN
1976     ...           NaN           NaN  3.627232e+10           NaN
1977     ...           NaN           NaN  4.233706e+10           NaN
1978     ...           NaN           NaN  4.650764e+10           NaN
1979     ...           NaN  1.192588e+08  5.575055e+10           NaN
1980     ...           NaN  1.134232e+08  6.713512e+10           NaN
1981     ...           NaN  9.874641e+07  7.549883e+10           NaN
1982     ...           NaN  9.814464e+07  7.669365e+10           NaN
1983     ...           NaN  1.101238e+08  7.858650e+10           NaN
1984     ...           NaN  1.355538e+08  5.595234e+10           NaN
1985     ...           NaN  1.236985e+08  5.793574e+10  1.409469e+10
1986     ...           NaN  1.186914e+08  5.891511e+10  2.633662e+10
1987     ...           NaN  1.308341e+08  4.534379e+10  3.665811e+10
1988     ...           NaN  1.485454e+08  5.842840e+10  2.542381e+10
1989     ...           NaN  1.444822e+08  4.214230e+10  6.293305e+09
1990     ...  1.336061e+10  1.583974e+08  4.702751e+10  6.471740e+09
1991     ...  1.367762e+10  1.888700e+08  5.173436e+10  9.613370e+09
1992     ...  1.294130e+10  1.961426e+08  5.847036e+10  9.866990e+09
1993     ...  1.309901e+10  1.880804e+08  5.810756e+10  1.318095e+10
1994     ...  1.289916e+10  2.192603e+08  5.652990e+10  1.628643e+10
1995     ...  1.335047e+10  2.339021e+08  7.488874e+10  2.073616e+10
1996     ...  1.394889e+10  2.451776e+08  6.825859e+10  2.465747e+10
1997     ...  1.474460e+10  2.558902e+08  8.583739e+10  2.684370e+10
1998     ...  1.498897e+10  2.623013e+08  9.133854e+10  2.720960e+10
1999     ...  1.707847e+10  2.679992e+08  9.797414e+10  2.868366e+10
2000     ...  1.376037e+10  2.720147e+08  1.171476e+11  3.364009e+10
2001     ...  1.140135e+10  2.579269e+08  1.229097e+11  3.529135e+10
2002     ...  9.687951e+09  2.626038e+08  9.288959e+10  3.794790e+10
2003     ...  1.012811e+10  3.144631e+08  8.362219e+10  4.271707e+10
2004     ...  1.203002e+10  3.649969e+08  1.124514e+11  4.942411e+10
2005     ...  1.430751e+10  3.949626e+08  1.455135e+11  5.763326e+10
2006     ...  1.703090e+10  4.393768e+08  1.834775e+11  6.637166e+10
2007     ...  2.231139e+10  5.264283e+08  2.303642e+11  7.741443e+10
2008     ...  2.793403e+10  6.079586e+08  3.156002e+11  9.913030e+10
2009     ...  3.281683e+10  6.100666e+08  3.294190e+11  1.060146e+11
2010     ...  3.933277e+10  7.008043e+08  3.938015e+11  1.159317e+11
2011     ...  4.532432e+10  7.921497e+08  3.164822e+11  1.355395e+11
2012     ...  5.118344e+10  7.817029e+08  3.812862e+11  1.558200e+11
2013     ...  5.679566e+10  8.017876e+08  3.713366e+11  1.712220e+11
2014     ...  6.313285e+10  8.149546e+08           NaN  1.862047e+11
2015     ...  6.673280e+10           NaN           NaN  1.935994e+11

                                                                              \
country Virgin Islands (U.S.) West Bank and Gaza         World   Yemen, Rep.
year
1960             2.420000e+07                NaN  1.364643e+12           NaN
1961             2.570000e+07                NaN  1.420440e+12           NaN
1962             3.690000e+07                NaN  1.524573e+12           NaN
1963             4.140000e+07                NaN  1.638187e+12           NaN
1964             5.380000e+07                NaN  1.799675e+12           NaN
1965             6.650000e+07                NaN  1.959900e+12           NaN
1966             8.410000e+07                NaN  2.125397e+12           NaN
1967             1.154000e+08                NaN  2.262923e+12           NaN
1968             1.738000e+08                NaN  2.440549e+12           NaN
1969             2.113000e+08                NaN  2.686747e+12           NaN
1970             2.190000e+08                NaN  2.950656e+12           NaN
1971             2.570000e+08                NaN  3.259057e+12           NaN
1972             3.071000e+08                NaN  3.757853e+12           NaN
1973             3.516000e+08                NaN  4.578523e+12           NaN
1974             3.954000e+08                NaN  5.279355e+12           NaN
1975             3.998000e+08                NaN  5.880305e+12           NaN
1976             4.400000e+08                NaN  6.400883e+12           NaN
1977             4.618000e+08                NaN  7.237905e+12           NaN
1978             5.129000e+08                NaN  8.521725e+12           NaN
1979             6.067000e+08                NaN  9.903841e+12           NaN
1980             7.278000e+08                NaN  1.115409e+13           NaN
1981             8.218000e+08                NaN  1.144748e+13           NaN
1982             8.326000e+08                NaN  1.134460e+13           NaN
1983             9.169000e+08                NaN  1.160740e+13           NaN
1984             9.854000e+08                NaN  1.204953e+13           NaN
1985             9.904000e+08                NaN  1.267287e+13           NaN
1986             1.035600e+09                NaN  1.499712e+13           NaN
1987             1.147800e+09                NaN  1.706395e+13           NaN
1988             1.204600e+09                NaN  1.910918e+13           NaN
1989             1.343900e+09                NaN  2.006077e+13           NaN
1990             1.564700e+09                NaN  2.256312e+13  5.647252e+09
1991             1.671200e+09                NaN  2.389846e+13  5.930370e+09
1992             1.770900e+09                NaN  2.537482e+13  6.463650e+09
1993             1.996000e+09                NaN  2.580571e+13  5.368271e+09
1994                      NaN       2.843300e+09  2.770637e+13  4.167356e+09
1995                      NaN       3.282800e+09  3.065894e+13  4.258789e+09
1996                      NaN       3.409600e+09  3.132499e+13  5.785685e+09
1997                      NaN       3.759800e+09  3.124076e+13  6.839039e+09
1998                      NaN       4.067800e+09  3.112270e+13  6.325220e+09
1999                      NaN       4.271200e+09  3.228297e+13  7.641101e+09
2000                      NaN       4.313600e+09  3.332130e+13  9.636342e+09
2001                      NaN       4.003700e+09  3.313421e+13  9.854042e+09
2002                      NaN       3.555800e+09  3.441805e+13  1.069328e+10
2003                      NaN       3.968000e+09  3.865630e+13  1.177777e+10
2004                      NaN       4.329200e+09  4.355213e+13  1.387350e+10
2005                      NaN       4.831800e+09  4.714259e+13  1.675377e+10
2006                      NaN       4.910100e+09  5.107451e+13  1.908173e+10
2007                      NaN       5.505800e+09  5.758343e+13  2.563367e+10
2008                      NaN       6.673500e+09  6.312856e+13  3.039720e+10
2009                      NaN       7.268200e+09  5.983553e+13  2.845950e+10
2010                      NaN       8.913100e+09  6.564782e+13  3.090675e+10
2011                      NaN       1.045985e+10  7.284314e+13  3.107886e+10
2012                      NaN       1.127940e+10  7.442836e+13  3.207477e+10
2013                      NaN       1.247600e+10  7.643132e+13  3.595450e+10
2014                      NaN       1.271560e+10  7.810634e+13           NaN
2015                      NaN       1.267740e+10  7.343364e+13           NaN


country        Zambia      Zimbabwe
year
1960     6.987397e+08  1.052990e+09
1961     6.823597e+08  1.096647e+09
1962     6.792797e+08  1.117602e+09
1963     7.043397e+08  1.159512e+09
1964     8.226397e+08  1.217138e+09
1965     1.061200e+09  1.311436e+09
1966     1.239000e+09  1.281750e+09
1967     1.340639e+09  1.397002e+09
1968     1.573739e+09  1.479600e+09
1969     1.926399e+09  1.747999e+09
1970     1.788779e+09  1.884206e+09
1971     1.653259e+09  2.178716e+09
1972     1.872417e+09  2.677729e+09
1973     2.434255e+09  3.309354e+09
1974     2.910981e+09  3.982161e+09
1975     2.442672e+09  4.371301e+09
1976     2.742859e+09  4.318372e+09
1977     2.515297e+09  4.364382e+09
1978     2.811032e+09  4.351600e+09
1979     3.353445e+09  5.177459e+09
1980     3.884531e+09  6.678868e+09
1981     4.008126e+09  8.011374e+09
1982     3.871117e+09  8.539701e+09
1983     3.321048e+09  7.764067e+09
1984     2.719519e+09  6.352126e+09
1985     2.252455e+09  5.637259e+09
1986     1.664414e+09  6.217524e+09
1987     2.265251e+09  6.741215e+09
1988     3.728878e+09  7.814784e+09
1989     3.994673e+09  8.286323e+09
1990     3.288382e+09  8.783817e+09
1991     3.378882e+09  8.641482e+09
1992     3.181922e+09  6.751472e+09
1993     3.273238e+09  6.563813e+09
1994     3.656648e+09  6.890675e+09
1995     3.807067e+09  7.111271e+09
1996     3.597221e+09  8.553147e+09
1997     4.303282e+09  8.529572e+09
1998     3.537683e+09  6.401968e+09
1999     3.404312e+09  6.858013e+09
2000     3.600683e+09  6.689958e+09
2001     4.094481e+09  6.777385e+09
2002     4.193846e+09  6.342116e+09
2003     4.901840e+09  5.727592e+09
2004     6.221078e+09  5.805598e+09
2005     8.331870e+09  5.755215e+09
2006     1.275686e+10  5.443896e+09
2007     1.405696e+10  5.291950e+09
2008     1.791086e+10  4.415703e+09
2009     1.532834e+10  8.157077e+09
2010     2.026555e+10  9.422161e+09
2011     2.345952e+10  1.095623e+10
2012     2.550306e+10  1.239272e+10
2013     2.804552e+10  1.349023e+10
2014     2.713464e+10  1.419691e+10
2015     2.120156e+10  1.389294e+10

[56 rows x 504 columns]

In [22]:
world.unstack(level=0)

                      Population                                            \
year                        1960          1961          1962          1963
country
Afghanistan         8.994793e+06  9.164945e+06  9.343772e+06  9.531555e+06
Albania                      NaN           NaN           NaN           NaN
Algeria             1.112489e+07  1.140486e+07  1.169015e+07  1.198513e+07
Andorra                      NaN           NaN           NaN           NaN
Angola                       NaN           NaN           NaN           NaN
...                          ...           ...           ...           ...
West Bank and Gaza           NaN           NaN           NaN           NaN
World               3.035056e+09  3.076121e+09  3.129064e+09  3.193947e+09
Yemen, Rep.                  NaN           NaN           NaN           NaN
Zambia              3.049586e+06  3.142848e+06  3.240664e+06  3.342894e+06
Zimbabwe            3.752390e+06  3.876638e+06  4.006262e+06  4.140804e+06

                                                                            \
year                        1964          1965          1966          1967
country
Afghanistan         9.728645e+06  9.935358e+06  1.014884e+07  1.036860e+07
Albania                      NaN           NaN           NaN           NaN
Algeria             1.229597e+07  1.262695e+07  1.298027e+07  1.335420e+07
Andorra                      NaN           NaN           NaN           NaN
Angola                       NaN           NaN           NaN           NaN
...                          ...           ...           ...           ...
West Bank and Gaza           NaN           NaN           NaN           NaN
World               3.259355e+09  3.326054e+09  3.395866e+09  3.465297e+09
Yemen, Rep.                  NaN           NaN           NaN           NaN
Zambia              3.449266e+06  3.559687e+06  3.674088e+06  3.792864e+06
Zimbabwe            4.279561e+06  4.422132e+06  4.568320e+06  4.718612e+06

                                                ...           GDP  \
year                        1968          1969  ...          2006
country                                         ...
Afghanistan         1.059979e+07  1.084951e+07  ...  7.057598e+09
Albania                      NaN           NaN  ...  8.992642e+09
Algeria             1.374438e+07  1.414444e+07  ...  1.170273e+11
Andorra                      NaN           NaN  ...  3.536452e+09
Angola                       NaN           NaN  ...  4.178948e+10
...                          ...           ...  ...           ...
West Bank and Gaza           NaN           NaN  ...  4.910100e+09
World               3.535512e+09  3.609910e+09  ...  5.107451e+13
Yemen, Rep.                  NaN           NaN  ...  1.908173e+10
Zambia              3.916928e+06  4.047479e+06  ...  1.275686e+10
Zimbabwe            4.874113e+06  5.036321e+06  ...  5.443896e+09

                                                                            \
year                        2007          2008          2009          2010
country
Afghanistan         9.843842e+09  1.019053e+10  1.248694e+10  1.593680e+10
Albania             1.070101e+10  1.288135e+10  1.204421e+10  1.192695e+10
Algeria             1.349771e+11  1.710007e+11  1.372110e+11  1.612073e+11
Andorra             4.010785e+09  4.001349e+09  3.649863e+09  3.346317e+09
Angola              6.044892e+10  8.417803e+10  7.549238e+10  8.247091e+10
...                          ...           ...           ...           ...
West Bank and Gaza  5.505800e+09  6.673500e+09  7.268200e+09  8.913100e+09
World               5.758343e+13  6.312856e+13  5.983553e+13  6.564782e+13
Yemen, Rep.         2.563367e+10  3.039720e+10  2.845950e+10  3.090675e+10
Zambia              1.405696e+10  1.791086e+10  1.532834e+10  2.026555e+10
Zimbabwe            5.291950e+09  4.415703e+09  8.157077e+09  9.422161e+09

                                                                            \
year                        2011          2012          2013          2014
country
Afghanistan         1.793024e+10  2.053654e+10  2.004633e+10  2.005019e+10
Albania             1.289087e+10  1.231978e+10  1.278103e+10  1.327796e+10
Algeria             2.000131e+11  2.090474e+11  2.097035e+11  2.135185e+11
Andorra             3.427236e+09  3.146178e+09  3.249101e+09           NaN
Angola              1.041159e+11  1.153984e+11  1.249121e+11  1.267751e+11
...                          ...           ...           ...           ...
West Bank and Gaza  1.045985e+10  1.127940e+10  1.247600e+10  1.271560e+10
World               7.284314e+13  7.442836e+13  7.643132e+13  7.810634e+13
Yemen, Rep.         3.107886e+10  3.207477e+10  3.595450e+10           NaN
Zambia              2.345952e+10  2.550306e+10  2.804552e+10  2.713464e+10
Zimbabwe            1.095623e+10  1.239272e+10  1.349023e+10  1.419691e+10


year                        2015
country
Afghanistan         1.919944e+10
Albania             1.145560e+10
Algeria             1.668386e+11
Andorra                      NaN
Angola              1.026431e+11
...                          ...
West Bank and Gaza  1.267740e+10
World               7.343364e+13
Yemen, Rep.                  NaN
Zambia              2.120156e+10
Zimbabwe            1.389294e+10

[252 rows x 112 columns]

In [23]:
world.unstack(level=1)

         Population                                              \
country Afghanistan    Albania     Algeria  Andorra      Angola
year
1960      8994793.0        NaN  11124892.0      NaN         NaN
1961      9164945.0        NaN  11404859.0      NaN         NaN
1962      9343772.0        NaN  11690152.0      NaN         NaN
1963      9531555.0        NaN  11985130.0      NaN         NaN
1964      9728645.0        NaN  12295973.0      NaN         NaN
1965      9935358.0        NaN  12626953.0      NaN         NaN
1966     10148841.0        NaN  12980269.0      NaN         NaN
1967     10368600.0        NaN  13354197.0      NaN         NaN
1968     10599790.0        NaN  13744383.0      NaN         NaN
1969     10849510.0        NaN  14144437.0      NaN         NaN
1970     11121097.0        NaN  14550033.0  24279.0         NaN
1971     11412821.0        NaN  14960111.0  25560.0         NaN
1972     11716896.0        NaN  15377095.0  26892.0         NaN
1973     12022514.0        NaN  15804428.0  28231.0         NaN
1974     12315553.0        NaN  16247113.0  29514.0         NaN
1975     12582954.0        NaN  16709098.0  30706.0         NaN
1976     12831361.0        NaN  17190236.0  31781.0         NaN
1977     13056499.0        NaN  17690184.0  32769.0         NaN
1978     13222547.0        NaN  18212331.0  33746.0         NaN
1979     13283279.0        NaN  18760761.0  34819.0         NaN
1980     13211412.0        NaN  19337723.0  36063.0         NaN
1981     12996923.0        NaN  19943667.0  37502.0         NaN
1982            NaN        NaN  20575701.0  39112.0         NaN
1983            NaN        NaN  21228288.0  40862.0         NaN
1984            NaN  2904429.0  21893857.0  42704.0         NaN
1985            NaN  2964762.0  22565908.0  44597.0   9745209.0
1986            NaN  3022635.0  23241276.0  46515.0  10023700.0
1987            NaN  3083605.0  23917889.0  48458.0  10285712.0
1988            NaN  3142336.0  24591493.0  50431.0  10544904.0
1989            NaN  3227943.0  25257671.0  52449.0  10820992.0
1990            NaN  3286542.0  25912364.0  54511.0  11127870.0
1991            NaN  3266790.0  26554277.0  56674.0  11472173.0
1992            NaN  3247039.0  27180921.0  58904.0  11848971.0
1993            NaN  3227287.0  27785977.0  61003.0  12246786.0
1994            NaN  3207536.0  28362015.0  62707.0  12648483.0
1995            NaN  3187784.0  28904300.0  63854.0  13042666.0
1996            NaN  3168033.0  29411839.0  64291.0  13424813.0
1997            NaN  3148281.0  29887717.0  64147.0  13801868.0
1998            NaN  3128530.0  30336880.0  63888.0  14187710.0
1999            NaN  3108778.0  30766551.0  64161.0  14601983.0
2000            NaN  3089027.0  31183658.0  65399.0  15058638.0
2001     20531160.0  3060173.0  31590320.0  67770.0  15562791.0
2002     21487079.0  3051010.0  31990387.0  71046.0  16109696.0
2003     22507368.0  3039616.0  32394886.0  74783.0  16691395.0
2004     23499850.0  3026939.0  32817225.0  78337.0  17295500.0
2005     24399948.0  3011487.0  33267887.0  81223.0  17912942.0
2006     25183615.0  2992547.0  33749328.0  83373.0  18541467.0
2007     25877544.0  2970017.0  34261971.0  84878.0  19183907.0
2008     26528741.0  2947314.0  34811059.0  85616.0  19842251.0
2009     27207291.0  2927519.0  35401790.0  85474.0  20520103.0
2010     27962207.0  2913021.0  36036159.0  84419.0  21219954.0
2011     28809167.0  2904780.0  36717132.0  82326.0  21942296.0
2012     29726803.0  2900247.0  37439427.0  79316.0  22685632.0
2013     30682500.0  2896652.0  38186135.0  75902.0  23448202.0
2014     31627506.0  2893654.0  38934334.0      NaN  24227524.0
2015     32526562.0  2889167.0  39666519.0      NaN  25021974.0

                                                                           \
country Antigua and Barbuda   Arab World   Argentina    Armenia     Aruba
year
1960                    NaN          NaN         NaN        NaN       NaN
1961                    NaN          NaN         NaN        NaN       NaN
1962                    NaN          NaN  21287682.0        NaN       NaN
1963                    NaN          NaN  21621845.0        NaN       NaN
1964                    NaN          NaN  21953926.0        NaN       NaN
1965                    NaN          NaN  22283389.0        NaN       NaN
1966                    NaN          NaN  22608747.0        NaN       NaN
1967                    NaN          NaN  22932201.0        NaN       NaN
1968                    NaN  115557094.0  23261273.0        NaN       NaN
1969                    NaN  118823872.0  23605992.0        NaN       NaN
1970                    NaN  122128175.0  23973062.0        NaN       NaN
1971                    NaN  125439089.0  24366442.0        NaN       NaN
1972                    NaN  128801209.0  24782950.0        NaN       NaN
1973                    NaN  132298955.0  25213388.0        NaN       NaN
1974                    NaN  136044481.0  25644505.0        NaN       NaN
1975                    NaN  140114424.0  26066975.0        NaN       NaN
1976                    NaN  144542039.0  26477153.0        NaN       NaN
1977                70223.0  149296257.0  26878567.0        NaN       NaN
1978                70508.0  154303887.0  27277742.0        NaN       NaN
1979                70553.0  159455867.0  27684530.0        NaN       NaN
1980                70301.0  164670713.0  28105889.0        NaN       NaN
1981                69750.0  169926632.0  28543366.0        NaN       NaN
1982                68950.0  175237742.0  28993989.0        NaN       NaN
1983                67958.0  180606318.0  29454739.0        NaN       NaN
1984                66863.0  186005735.0  29920907.0        NaN       NaN
1985                65744.0  191564251.0  30388781.0        NaN       NaN
1986                64605.0  197202142.0  30857242.0        NaN       NaN
1987                63484.0  202851923.0  31326473.0        NaN       NaN
1988                62538.0  208546282.0  31795515.0        NaN       NaN
1989                61967.0  214250542.0  32263559.0        NaN       NaN
1990                61906.0  222117305.0  32729740.0  3544695.0       NaN
1991                62412.0  228171034.0  33193920.0  3511912.0       NaN
1992                63434.0  232417246.0  33655149.0  3449497.0       NaN
1993                64868.0  238628852.0  34110912.0  3369673.0       NaN
1994                66550.0  244893420.0  34558114.0  3289943.0   76700.0
1995                68349.0  252591048.0  34994818.0  3223173.0   80326.0
1996                70245.0  258423164.0  35419683.0  3173425.0   83195.0
1997                72232.0  264153948.0  35833965.0  3137652.0   85447.0
1998                74206.0  269795252.0  36241578.0  3112958.0   87276.0
1999                76041.0  275503565.0  36648054.0  3093820.0   89004.0
2000                77648.0  281326250.0  37057453.0  3076098.0   90858.0
2001                78972.0  287291826.0  37471535.0  3060036.0   92894.0
2002                80030.0  293402563.0  37889443.0  3047249.0   94995.0
2003                80904.0  299731956.0  38309475.0  3036420.0   97015.0
2004                81718.0  306387415.0  38728778.0  3025982.0   98742.0
2005                82565.0  313430911.0  39145491.0  3014917.0  100031.0
2006                83467.0  320906736.0  39558750.0  3002161.0  100830.0
2007                84397.0  328766559.0  39969903.0  2988117.0  101218.0
2008                85350.0  336886468.0  40381860.0  2975029.0  101342.0
2009                86300.0  345054176.0  40798641.0  2966108.0  101416.0
2010                87233.0  353112237.0  41222875.0  2963496.0  101597.0
2011                88152.0  361031820.0  41655616.0  2967984.0  101936.0
2012                89069.0  368802611.0  42095224.0  2978339.0       NaN
2013                89985.0  376504253.0  42538304.0  2992192.0       NaN
2014                90900.0  384222592.0  42980026.0  3006154.0       NaN
2015                91818.0  392022276.0         NaN  3017712.0       NaN

         ...           GDP                                            \
country  ...    Uzbekistan       Vanuatu Venezuela, RB       Vietnam
year     ...
1960     ...           NaN           NaN  8.607600e+09           NaN
1961     ...           NaN           NaN  8.923367e+09           NaN
1962     ...           NaN           NaN  9.873398e+09           NaN
1963     ...           NaN           NaN  1.066338e+10           NaN
1964     ...           NaN           NaN  9.113581e+09           NaN
1965     ...           NaN           NaN  9.602945e+09           NaN
1966     ...           NaN           NaN  1.009657e+10           NaN
1967     ...           NaN           NaN  1.047278e+10           NaN
1968     ...           NaN           NaN  1.147091e+10           NaN
1969     ...           NaN           NaN  1.192757e+10           NaN
1970     ...           NaN           NaN  1.299312e+10           NaN
1971     ...           NaN           NaN  1.447156e+10           NaN
1972     ...           NaN           NaN  1.592287e+10           NaN
1973     ...           NaN           NaN  1.944593e+10           NaN
1974     ...           NaN           NaN  2.908710e+10           NaN
1975     ...           NaN           NaN  3.141316e+10           NaN
1976     ...           NaN           NaN  3.627232e+10           NaN
1977     ...           NaN           NaN  4.233706e+10           NaN
1978     ...           NaN           NaN  4.650764e+10           NaN
1979     ...           NaN  1.192588e+08  5.575055e+10           NaN
1980     ...           NaN  1.134232e+08  6.713512e+10           NaN
1981     ...           NaN  9.874641e+07  7.549883e+10           NaN
1982     ...           NaN  9.814464e+07  7.669365e+10           NaN
1983     ...           NaN  1.101238e+08  7.858650e+10           NaN
1984     ...           NaN  1.355538e+08  5.595234e+10           NaN
1985     ...           NaN  1.236985e+08  5.793574e+10  1.409469e+10
1986     ...           NaN  1.186914e+08  5.891511e+10  2.633662e+10
1987     ...           NaN  1.308341e+08  4.534379e+10  3.665811e+10
1988     ...           NaN  1.485454e+08  5.842840e+10  2.542381e+10
1989     ...           NaN  1.444822e+08  4.214230e+10  6.293305e+09
1990     ...  1.336061e+10  1.583974e+08  4.702751e+10  6.471740e+09
1991     ...  1.367762e+10  1.888700e+08  5.173436e+10  9.613370e+09
1992     ...  1.294130e+10  1.961426e+08  5.847036e+10  9.866990e+09
1993     ...  1.309901e+10  1.880804e+08  5.810756e+10  1.318095e+10
1994     ...  1.289916e+10  2.192603e+08  5.652990e+10  1.628643e+10
1995     ...  1.335047e+10  2.339021e+08  7.488874e+10  2.073616e+10
1996     ...  1.394889e+10  2.451776e+08  6.825859e+10  2.465747e+10
1997     ...  1.474460e+10  2.558902e+08  8.583739e+10  2.684370e+10
1998     ...  1.498897e+10  2.623013e+08  9.133854e+10  2.720960e+10
1999     ...  1.707847e+10  2.679992e+08  9.797414e+10  2.868366e+10
2000     ...  1.376037e+10  2.720147e+08  1.171476e+11  3.364009e+10
2001     ...  1.140135e+10  2.579269e+08  1.229097e+11  3.529135e+10
2002     ...  9.687951e+09  2.626038e+08  9.288959e+10  3.794790e+10
2003     ...  1.012811e+10  3.144631e+08  8.362219e+10  4.271707e+10
2004     ...  1.203002e+10  3.649969e+08  1.124514e+11  4.942411e+10
2005     ...  1.430751e+10  3.949626e+08  1.455135e+11  5.763326e+10
2006     ...  1.703090e+10  4.393768e+08  1.834775e+11  6.637166e+10
2007     ...  2.231139e+10  5.264283e+08  2.303642e+11  7.741443e+10
2008     ...  2.793403e+10  6.079586e+08  3.156002e+11  9.913030e+10
2009     ...  3.281683e+10  6.100666e+08  3.294190e+11  1.060146e+11
2010     ...  3.933277e+10  7.008043e+08  3.938015e+11  1.159317e+11
2011     ...  4.532432e+10  7.921497e+08  3.164822e+11  1.355395e+11
2012     ...  5.118344e+10  7.817029e+08  3.812862e+11  1.558200e+11
2013     ...  5.679566e+10  8.017876e+08  3.713366e+11  1.712220e+11
2014     ...  6.313285e+10  8.149546e+08           NaN  1.862047e+11
2015     ...  6.673280e+10           NaN           NaN  1.935994e+11

                                                                              \
country Virgin Islands (U.S.) West Bank and Gaza         World   Yemen, Rep.
year
1960             2.420000e+07                NaN  1.364643e+12           NaN
1961             2.570000e+07                NaN  1.420440e+12           NaN
1962             3.690000e+07                NaN  1.524573e+12           NaN
1963             4.140000e+07                NaN  1.638187e+12           NaN
1964             5.380000e+07                NaN  1.799675e+12           NaN
1965             6.650000e+07                NaN  1.959900e+12           NaN
1966             8.410000e+07                NaN  2.125397e+12           NaN
1967             1.154000e+08                NaN  2.262923e+12           NaN
1968             1.738000e+08                NaN  2.440549e+12           NaN
1969             2.113000e+08                NaN  2.686747e+12           NaN
1970             2.190000e+08                NaN  2.950656e+12           NaN
1971             2.570000e+08                NaN  3.259057e+12           NaN
1972             3.071000e+08                NaN  3.757853e+12           NaN
1973             3.516000e+08                NaN  4.578523e+12           NaN
1974             3.954000e+08                NaN  5.279355e+12           NaN
1975             3.998000e+08                NaN  5.880305e+12           NaN
1976             4.400000e+08                NaN  6.400883e+12           NaN
1977             4.618000e+08                NaN  7.237905e+12           NaN
1978             5.129000e+08                NaN  8.521725e+12           NaN
1979             6.067000e+08                NaN  9.903841e+12           NaN
1980             7.278000e+08                NaN  1.115409e+13           NaN
1981             8.218000e+08                NaN  1.144748e+13           NaN
1982             8.326000e+08                NaN  1.134460e+13           NaN
1983             9.169000e+08                NaN  1.160740e+13           NaN
1984             9.854000e+08                NaN  1.204953e+13           NaN
1985             9.904000e+08                NaN  1.267287e+13           NaN
1986             1.035600e+09                NaN  1.499712e+13           NaN
1987             1.147800e+09                NaN  1.706395e+13           NaN
1988             1.204600e+09                NaN  1.910918e+13           NaN
1989             1.343900e+09                NaN  2.006077e+13           NaN
1990             1.564700e+09                NaN  2.256312e+13  5.647252e+09
1991             1.671200e+09                NaN  2.389846e+13  5.930370e+09
1992             1.770900e+09                NaN  2.537482e+13  6.463650e+09
1993             1.996000e+09                NaN  2.580571e+13  5.368271e+09
1994                      NaN       2.843300e+09  2.770637e+13  4.167356e+09
1995                      NaN       3.282800e+09  3.065894e+13  4.258789e+09
1996                      NaN       3.409600e+09  3.132499e+13  5.785685e+09
1997                      NaN       3.759800e+09  3.124076e+13  6.839039e+09
1998                      NaN       4.067800e+09  3.112270e+13  6.325220e+09
1999                      NaN       4.271200e+09  3.228297e+13  7.641101e+09
2000                      NaN       4.313600e+09  3.332130e+13  9.636342e+09
2001                      NaN       4.003700e+09  3.313421e+13  9.854042e+09
2002                      NaN       3.555800e+09  3.441805e+13  1.069328e+10
2003                      NaN       3.968000e+09  3.865630e+13  1.177777e+10
2004                      NaN       4.329200e+09  4.355213e+13  1.387350e+10
2005                      NaN       4.831800e+09  4.714259e+13  1.675377e+10
2006                      NaN       4.910100e+09  5.107451e+13  1.908173e+10
2007                      NaN       5.505800e+09  5.758343e+13  2.563367e+10
2008                      NaN       6.673500e+09  6.312856e+13  3.039720e+10
2009                      NaN       7.268200e+09  5.983553e+13  2.845950e+10
2010                      NaN       8.913100e+09  6.564782e+13  3.090675e+10
2011                      NaN       1.045985e+10  7.284314e+13  3.107886e+10
2012                      NaN       1.127940e+10  7.442836e+13  3.207477e+10
2013                      NaN       1.247600e+10  7.643132e+13  3.595450e+10
2014                      NaN       1.271560e+10  7.810634e+13           NaN
2015                      NaN       1.267740e+10  7.343364e+13           NaN


country        Zambia      Zimbabwe
year
1960     6.987397e+08  1.052990e+09
1961     6.823597e+08  1.096647e+09
1962     6.792797e+08  1.117602e+09
1963     7.043397e+08  1.159512e+09
1964     8.226397e+08  1.217138e+09
1965     1.061200e+09  1.311436e+09
1966     1.239000e+09  1.281750e+09
1967     1.340639e+09  1.397002e+09
1968     1.573739e+09  1.479600e+09
1969     1.926399e+09  1.747999e+09
1970     1.788779e+09  1.884206e+09
1971     1.653259e+09  2.178716e+09
1972     1.872417e+09  2.677729e+09
1973     2.434255e+09  3.309354e+09
1974     2.910981e+09  3.982161e+09
1975     2.442672e+09  4.371301e+09
1976     2.742859e+09  4.318372e+09
1977     2.515297e+09  4.364382e+09
1978     2.811032e+09  4.351600e+09
1979     3.353445e+09  5.177459e+09
1980     3.884531e+09  6.678868e+09
1981     4.008126e+09  8.011374e+09
1982     3.871117e+09  8.539701e+09
1983     3.321048e+09  7.764067e+09
1984     2.719519e+09  6.352126e+09
1985     2.252455e+09  5.637259e+09
1986     1.664414e+09  6.217524e+09
1987     2.265251e+09  6.741215e+09
1988     3.728878e+09  7.814784e+09
1989     3.994673e+09  8.286323e+09
1990     3.288382e+09  8.783817e+09
1991     3.378882e+09  8.641482e+09
1992     3.181922e+09  6.751472e+09
1993     3.273238e+09  6.563813e+09
1994     3.656648e+09  6.890675e+09
1995     3.807067e+09  7.111271e+09
1996     3.597221e+09  8.553147e+09
1997     4.303282e+09  8.529572e+09
1998     3.537683e+09  6.401968e+09
1999     3.404312e+09  6.858013e+09
2000     3.600683e+09  6.689958e+09
2001     4.094481e+09  6.777385e+09
2002     4.193846e+09  6.342116e+09
2003     4.901840e+09  5.727592e+09
2004     6.221078e+09  5.805598e+09
2005     8.331870e+09  5.755215e+09
2006     1.275686e+10  5.443896e+09
2007     1.405696e+10  5.291950e+09
2008     1.791086e+10  4.415703e+09
2009     1.532834e+10  8.157077e+09
2010     2.026555e+10  9.422161e+09
2011     2.345952e+10  1.095623e+10
2012     2.550306e+10  1.239272e+10
2013     2.804552e+10  1.349023e+10
2014     2.713464e+10  1.419691e+10
2015     2.120156e+10  1.389294e+10

[56 rows x 504 columns]

In [27]:
world.unstack(level="year")
world.unstack(level="country")
world.unstack(level=1)

         Population                                              \
country Afghanistan    Albania     Algeria  Andorra      Angola
year
1960      8994793.0        NaN  11124892.0      NaN         NaN
1961      9164945.0        NaN  11404859.0      NaN         NaN
1962      9343772.0        NaN  11690152.0      NaN         NaN
1963      9531555.0        NaN  11985130.0      NaN         NaN
1964      9728645.0        NaN  12295973.0      NaN         NaN
1965      9935358.0        NaN  12626953.0      NaN         NaN
1966     10148841.0        NaN  12980269.0      NaN         NaN
1967     10368600.0        NaN  13354197.0      NaN         NaN
1968     10599790.0        NaN  13744383.0      NaN         NaN
1969     10849510.0        NaN  14144437.0      NaN         NaN
1970     11121097.0        NaN  14550033.0  24279.0         NaN
1971     11412821.0        NaN  14960111.0  25560.0         NaN
1972     11716896.0        NaN  15377095.0  26892.0         NaN
1973     12022514.0        NaN  15804428.0  28231.0         NaN
1974     12315553.0        NaN  16247113.0  29514.0         NaN
1975     12582954.0        NaN  16709098.0  30706.0         NaN
1976     12831361.0        NaN  17190236.0  31781.0         NaN
1977     13056499.0        NaN  17690184.0  32769.0         NaN
1978     13222547.0        NaN  18212331.0  33746.0         NaN
1979     13283279.0        NaN  18760761.0  34819.0         NaN
1980     13211412.0        NaN  19337723.0  36063.0         NaN
1981     12996923.0        NaN  19943667.0  37502.0         NaN
1982            NaN        NaN  20575701.0  39112.0         NaN
1983            NaN        NaN  21228288.0  40862.0         NaN
1984            NaN  2904429.0  21893857.0  42704.0         NaN
1985            NaN  2964762.0  22565908.0  44597.0   9745209.0
1986            NaN  3022635.0  23241276.0  46515.0  10023700.0
1987            NaN  3083605.0  23917889.0  48458.0  10285712.0
1988            NaN  3142336.0  24591493.0  50431.0  10544904.0
1989            NaN  3227943.0  25257671.0  52449.0  10820992.0
1990            NaN  3286542.0  25912364.0  54511.0  11127870.0
1991            NaN  3266790.0  26554277.0  56674.0  11472173.0
1992            NaN  3247039.0  27180921.0  58904.0  11848971.0
1993            NaN  3227287.0  27785977.0  61003.0  12246786.0
1994            NaN  3207536.0  28362015.0  62707.0  12648483.0
1995            NaN  3187784.0  28904300.0  63854.0  13042666.0
1996            NaN  3168033.0  29411839.0  64291.0  13424813.0
1997            NaN  3148281.0  29887717.0  64147.0  13801868.0
1998            NaN  3128530.0  30336880.0  63888.0  14187710.0
1999            NaN  3108778.0  30766551.0  64161.0  14601983.0
2000            NaN  3089027.0  31183658.0  65399.0  15058638.0
2001     20531160.0  3060173.0  31590320.0  67770.0  15562791.0
2002     21487079.0  3051010.0  31990387.0  71046.0  16109696.0
2003     22507368.0  3039616.0  32394886.0  74783.0  16691395.0
2004     23499850.0  3026939.0  32817225.0  78337.0  17295500.0
2005     24399948.0  3011487.0  33267887.0  81223.0  17912942.0
2006     25183615.0  2992547.0  33749328.0  83373.0  18541467.0
2007     25877544.0  2970017.0  34261971.0  84878.0  19183907.0
2008     26528741.0  2947314.0  34811059.0  85616.0  19842251.0
2009     27207291.0  2927519.0  35401790.0  85474.0  20520103.0
2010     27962207.0  2913021.0  36036159.0  84419.0  21219954.0
2011     28809167.0  2904780.0  36717132.0  82326.0  21942296.0
2012     29726803.0  2900247.0  37439427.0  79316.0  22685632.0
2013     30682500.0  2896652.0  38186135.0  75902.0  23448202.0
2014     31627506.0  2893654.0  38934334.0      NaN  24227524.0
2015     32526562.0  2889167.0  39666519.0      NaN  25021974.0

                                                                           \
country Antigua and Barbuda   Arab World   Argentina    Armenia     Aruba
year
1960                    NaN          NaN         NaN        NaN       NaN
1961                    NaN          NaN         NaN        NaN       NaN
1962                    NaN          NaN  21287682.0        NaN       NaN
1963                    NaN          NaN  21621845.0        NaN       NaN
1964                    NaN          NaN  21953926.0        NaN       NaN
1965                    NaN          NaN  22283389.0        NaN       NaN
1966                    NaN          NaN  22608747.0        NaN       NaN
1967                    NaN          NaN  22932201.0        NaN       NaN
1968                    NaN  115557094.0  23261273.0        NaN       NaN
1969                    NaN  118823872.0  23605992.0        NaN       NaN
1970                    NaN  122128175.0  23973062.0        NaN       NaN
1971                    NaN  125439089.0  24366442.0        NaN       NaN
1972                    NaN  128801209.0  24782950.0        NaN       NaN
1973                    NaN  132298955.0  25213388.0        NaN       NaN
1974                    NaN  136044481.0  25644505.0        NaN       NaN
1975                    NaN  140114424.0  26066975.0        NaN       NaN
1976                    NaN  144542039.0  26477153.0        NaN       NaN
1977                70223.0  149296257.0  26878567.0        NaN       NaN
1978                70508.0  154303887.0  27277742.0        NaN       NaN
1979                70553.0  159455867.0  27684530.0        NaN       NaN
1980                70301.0  164670713.0  28105889.0        NaN       NaN
1981                69750.0  169926632.0  28543366.0        NaN       NaN
1982                68950.0  175237742.0  28993989.0        NaN       NaN
1983                67958.0  180606318.0  29454739.0        NaN       NaN
1984                66863.0  186005735.0  29920907.0        NaN       NaN
1985                65744.0  191564251.0  30388781.0        NaN       NaN
1986                64605.0  197202142.0  30857242.0        NaN       NaN
1987                63484.0  202851923.0  31326473.0        NaN       NaN
1988                62538.0  208546282.0  31795515.0        NaN       NaN
1989                61967.0  214250542.0  32263559.0        NaN       NaN
1990                61906.0  222117305.0  32729740.0  3544695.0       NaN
1991                62412.0  228171034.0  33193920.0  3511912.0       NaN
1992                63434.0  232417246.0  33655149.0  3449497.0       NaN
1993                64868.0  238628852.0  34110912.0  3369673.0       NaN
1994                66550.0  244893420.0  34558114.0  3289943.0   76700.0
1995                68349.0  252591048.0  34994818.0  3223173.0   80326.0
1996                70245.0  258423164.0  35419683.0  3173425.0   83195.0
1997                72232.0  264153948.0  35833965.0  3137652.0   85447.0
1998                74206.0  269795252.0  36241578.0  3112958.0   87276.0
1999                76041.0  275503565.0  36648054.0  3093820.0   89004.0
2000                77648.0  281326250.0  37057453.0  3076098.0   90858.0
2001                78972.0  287291826.0  37471535.0  3060036.0   92894.0
2002                80030.0  293402563.0  37889443.0  3047249.0   94995.0
2003                80904.0  299731956.0  38309475.0  3036420.0   97015.0
2004                81718.0  306387415.0  38728778.0  3025982.0   98742.0
2005                82565.0  313430911.0  39145491.0  3014917.0  100031.0
2006                83467.0  320906736.0  39558750.0  3002161.0  100830.0
2007                84397.0  328766559.0  39969903.0  2988117.0  101218.0
2008                85350.0  336886468.0  40381860.0  2975029.0  101342.0
2009                86300.0  345054176.0  40798641.0  2966108.0  101416.0
2010                87233.0  353112237.0  41222875.0  2963496.0  101597.0
2011                88152.0  361031820.0  41655616.0  2967984.0  101936.0
2012                89069.0  368802611.0  42095224.0  2978339.0       NaN
2013                89985.0  376504253.0  42538304.0  2992192.0       NaN
2014                90900.0  384222592.0  42980026.0  3006154.0       NaN
2015                91818.0  392022276.0         NaN  3017712.0       NaN

         ...           GDP                                            \
country  ...    Uzbekistan       Vanuatu Venezuela, RB       Vietnam
year     ...
1960     ...           NaN           NaN  8.607600e+09           NaN
1961     ...           NaN           NaN  8.923367e+09           NaN
1962     ...           NaN           NaN  9.873398e+09           NaN
1963     ...           NaN           NaN  1.066338e+10           NaN
1964     ...           NaN           NaN  9.113581e+09           NaN
1965     ...           NaN           NaN  9.602945e+09           NaN
1966     ...           NaN           NaN  1.009657e+10           NaN
1967     ...           NaN           NaN  1.047278e+10           NaN
1968     ...           NaN           NaN  1.147091e+10           NaN
1969     ...           NaN           NaN  1.192757e+10           NaN
1970     ...           NaN           NaN  1.299312e+10           NaN
1971     ...           NaN           NaN  1.447156e+10           NaN
1972     ...           NaN           NaN  1.592287e+10           NaN
1973     ...           NaN           NaN  1.944593e+10           NaN
1974     ...           NaN           NaN  2.908710e+10           NaN
1975     ...           NaN           NaN  3.141316e+10           NaN
1976     ...           NaN           NaN  3.627232e+10           NaN
1977     ...           NaN           NaN  4.233706e+10           NaN
1978     ...           NaN           NaN  4.650764e+10           NaN
1979     ...           NaN  1.192588e+08  5.575055e+10           NaN
1980     ...           NaN  1.134232e+08  6.713512e+10           NaN
1981     ...           NaN  9.874641e+07  7.549883e+10           NaN
1982     ...           NaN  9.814464e+07  7.669365e+10           NaN
1983     ...           NaN  1.101238e+08  7.858650e+10           NaN
1984     ...           NaN  1.355538e+08  5.595234e+10           NaN
1985     ...           NaN  1.236985e+08  5.793574e+10  1.409469e+10
1986     ...           NaN  1.186914e+08  5.891511e+10  2.633662e+10
1987     ...           NaN  1.308341e+08  4.534379e+10  3.665811e+10
1988     ...           NaN  1.485454e+08  5.842840e+10  2.542381e+10
1989     ...           NaN  1.444822e+08  4.214230e+10  6.293305e+09
1990     ...  1.336061e+10  1.583974e+08  4.702751e+10  6.471740e+09
1991     ...  1.367762e+10  1.888700e+08  5.173436e+10  9.613370e+09
1992     ...  1.294130e+10  1.961426e+08  5.847036e+10  9.866990e+09
1993     ...  1.309901e+10  1.880804e+08  5.810756e+10  1.318095e+10
1994     ...  1.289916e+10  2.192603e+08  5.652990e+10  1.628643e+10
1995     ...  1.335047e+10  2.339021e+08  7.488874e+10  2.073616e+10
1996     ...  1.394889e+10  2.451776e+08  6.825859e+10  2.465747e+10
1997     ...  1.474460e+10  2.558902e+08  8.583739e+10  2.684370e+10
1998     ...  1.498897e+10  2.623013e+08  9.133854e+10  2.720960e+10
1999     ...  1.707847e+10  2.679992e+08  9.797414e+10  2.868366e+10
2000     ...  1.376037e+10  2.720147e+08  1.171476e+11  3.364009e+10
2001     ...  1.140135e+10  2.579269e+08  1.229097e+11  3.529135e+10
2002     ...  9.687951e+09  2.626038e+08  9.288959e+10  3.794790e+10
2003     ...  1.012811e+10  3.144631e+08  8.362219e+10  4.271707e+10
2004     ...  1.203002e+10  3.649969e+08  1.124514e+11  4.942411e+10
2005     ...  1.430751e+10  3.949626e+08  1.455135e+11  5.763326e+10
2006     ...  1.703090e+10  4.393768e+08  1.834775e+11  6.637166e+10
2007     ...  2.231139e+10  5.264283e+08  2.303642e+11  7.741443e+10
2008     ...  2.793403e+10  6.079586e+08  3.156002e+11  9.913030e+10
2009     ...  3.281683e+10  6.100666e+08  3.294190e+11  1.060146e+11
2010     ...  3.933277e+10  7.008043e+08  3.938015e+11  1.159317e+11
2011     ...  4.532432e+10  7.921497e+08  3.164822e+11  1.355395e+11
2012     ...  5.118344e+10  7.817029e+08  3.812862e+11  1.558200e+11
2013     ...  5.679566e+10  8.017876e+08  3.713366e+11  1.712220e+11
2014     ...  6.313285e+10  8.149546e+08           NaN  1.862047e+11
2015     ...  6.673280e+10           NaN           NaN  1.935994e+11

                                                                              \
country Virgin Islands (U.S.) West Bank and Gaza         World   Yemen, Rep.
year
1960             2.420000e+07                NaN  1.364643e+12           NaN
1961             2.570000e+07                NaN  1.420440e+12           NaN
1962             3.690000e+07                NaN  1.524573e+12           NaN
1963             4.140000e+07                NaN  1.638187e+12           NaN
1964             5.380000e+07                NaN  1.799675e+12           NaN
1965             6.650000e+07                NaN  1.959900e+12           NaN
1966             8.410000e+07                NaN  2.125397e+12           NaN
1967             1.154000e+08                NaN  2.262923e+12           NaN
1968             1.738000e+08                NaN  2.440549e+12           NaN
1969             2.113000e+08                NaN  2.686747e+12           NaN
1970             2.190000e+08                NaN  2.950656e+12           NaN
1971             2.570000e+08                NaN  3.259057e+12           NaN
1972             3.071000e+08                NaN  3.757853e+12           NaN
1973             3.516000e+08                NaN  4.578523e+12           NaN
1974             3.954000e+08                NaN  5.279355e+12           NaN
1975             3.998000e+08                NaN  5.880305e+12           NaN
1976             4.400000e+08                NaN  6.400883e+12           NaN
1977             4.618000e+08                NaN  7.237905e+12           NaN
1978             5.129000e+08                NaN  8.521725e+12           NaN
1979             6.067000e+08                NaN  9.903841e+12           NaN
1980             7.278000e+08                NaN  1.115409e+13           NaN
1981             8.218000e+08                NaN  1.144748e+13           NaN
1982             8.326000e+08                NaN  1.134460e+13           NaN
1983             9.169000e+08                NaN  1.160740e+13           NaN
1984             9.854000e+08                NaN  1.204953e+13           NaN
1985             9.904000e+08                NaN  1.267287e+13           NaN
1986             1.035600e+09                NaN  1.499712e+13           NaN
1987             1.147800e+09                NaN  1.706395e+13           NaN
1988             1.204600e+09                NaN  1.910918e+13           NaN
1989             1.343900e+09                NaN  2.006077e+13           NaN
1990             1.564700e+09                NaN  2.256312e+13  5.647252e+09
1991             1.671200e+09                NaN  2.389846e+13  5.930370e+09
1992             1.770900e+09                NaN  2.537482e+13  6.463650e+09
1993             1.996000e+09                NaN  2.580571e+13  5.368271e+09
1994                      NaN       2.843300e+09  2.770637e+13  4.167356e+09
1995                      NaN       3.282800e+09  3.065894e+13  4.258789e+09
1996                      NaN       3.409600e+09  3.132499e+13  5.785685e+09
1997                      NaN       3.759800e+09  3.124076e+13  6.839039e+09
1998                      NaN       4.067800e+09  3.112270e+13  6.325220e+09
1999                      NaN       4.271200e+09  3.228297e+13  7.641101e+09
2000                      NaN       4.313600e+09  3.332130e+13  9.636342e+09
2001                      NaN       4.003700e+09  3.313421e+13  9.854042e+09
2002                      NaN       3.555800e+09  3.441805e+13  1.069328e+10
2003                      NaN       3.968000e+09  3.865630e+13  1.177777e+10
2004                      NaN       4.329200e+09  4.355213e+13  1.387350e+10
2005                      NaN       4.831800e+09  4.714259e+13  1.675377e+10
2006                      NaN       4.910100e+09  5.107451e+13  1.908173e+10
2007                      NaN       5.505800e+09  5.758343e+13  2.563367e+10
2008                      NaN       6.673500e+09  6.312856e+13  3.039720e+10
2009                      NaN       7.268200e+09  5.983553e+13  2.845950e+10
2010                      NaN       8.913100e+09  6.564782e+13  3.090675e+10
2011                      NaN       1.045985e+10  7.284314e+13  3.107886e+10
2012                      NaN       1.127940e+10  7.442836e+13  3.207477e+10
2013                      NaN       1.247600e+10  7.643132e+13  3.595450e+10
2014                      NaN       1.271560e+10  7.810634e+13           NaN
2015                      NaN       1.267740e+10  7.343364e+13           NaN


country        Zambia      Zimbabwe
year
1960     6.987397e+08  1.052990e+09
1961     6.823597e+08  1.096647e+09
1962     6.792797e+08  1.117602e+09
1963     7.043397e+08  1.159512e+09
1964     8.226397e+08  1.217138e+09
1965     1.061200e+09  1.311436e+09
1966     1.239000e+09  1.281750e+09
1967     1.340639e+09  1.397002e+09
1968     1.573739e+09  1.479600e+09
1969     1.926399e+09  1.747999e+09
1970     1.788779e+09  1.884206e+09
1971     1.653259e+09  2.178716e+09
1972     1.872417e+09  2.677729e+09
1973     2.434255e+09  3.309354e+09
1974     2.910981e+09  3.982161e+09
1975     2.442672e+09  4.371301e+09
1976     2.742859e+09  4.318372e+09
1977     2.515297e+09  4.364382e+09
1978     2.811032e+09  4.351600e+09
1979     3.353445e+09  5.177459e+09
1980     3.884531e+09  6.678868e+09
1981     4.008126e+09  8.011374e+09
1982     3.871117e+09  8.539701e+09
1983     3.321048e+09  7.764067e+09
1984     2.719519e+09  6.352126e+09
1985     2.252455e+09  5.637259e+09
1986     1.664414e+09  6.217524e+09
1987     2.265251e+09  6.741215e+09
1988     3.728878e+09  7.814784e+09
1989     3.994673e+09  8.286323e+09
1990     3.288382e+09  8.783817e+09
1991     3.378882e+09  8.641482e+09
1992     3.181922e+09  6.751472e+09
1993     3.273238e+09  6.563813e+09
1994     3.656648e+09  6.890675e+09
1995     3.807067e+09  7.111271e+09
1996     3.597221e+09  8.553147e+09
1997     4.303282e+09  8.529572e+09
1998     3.537683e+09  6.401968e+09
1999     3.404312e+09  6.858013e+09
2000     3.600683e+09  6.689958e+09
2001     4.094481e+09  6.777385e+09
2002     4.193846e+09  6.342116e+09
2003     4.901840e+09  5.727592e+09
2004     6.221078e+09  5.805598e+09
2005     8.331870e+09  5.755215e+09
2006     1.275686e+10  5.443896e+09
2007     1.405696e+10  5.291950e+09
2008     1.791086e+10  4.415703e+09
2009     1.532834e+10  8.157077e+09
2010     2.026555e+10  9.422161e+09
2011     2.345952e+10  1.095623e+10
2012     2.550306e+10  1.239272e+10
2013     2.804552e+10  1.349023e+10
2014     2.713464e+10  1.419691e+10
2015     2.120156e+10  1.389294e+10

[56 rows x 504 columns]

In [29]:
world.unstack(level=-1)

         Population                                              \
country Afghanistan    Albania     Algeria  Andorra      Angola
year
1960      8994793.0        NaN  11124892.0      NaN         NaN
1961      9164945.0        NaN  11404859.0      NaN         NaN
1962      9343772.0        NaN  11690152.0      NaN         NaN
1963      9531555.0        NaN  11985130.0      NaN         NaN
1964      9728645.0        NaN  12295973.0      NaN         NaN
1965      9935358.0        NaN  12626953.0      NaN         NaN
1966     10148841.0        NaN  12980269.0      NaN         NaN
1967     10368600.0        NaN  13354197.0      NaN         NaN
1968     10599790.0        NaN  13744383.0      NaN         NaN
1969     10849510.0        NaN  14144437.0      NaN         NaN
1970     11121097.0        NaN  14550033.0  24279.0         NaN
1971     11412821.0        NaN  14960111.0  25560.0         NaN
1972     11716896.0        NaN  15377095.0  26892.0         NaN
1973     12022514.0        NaN  15804428.0  28231.0         NaN
1974     12315553.0        NaN  16247113.0  29514.0         NaN
1975     12582954.0        NaN  16709098.0  30706.0         NaN
1976     12831361.0        NaN  17190236.0  31781.0         NaN
1977     13056499.0        NaN  17690184.0  32769.0         NaN
1978     13222547.0        NaN  18212331.0  33746.0         NaN
1979     13283279.0        NaN  18760761.0  34819.0         NaN
1980     13211412.0        NaN  19337723.0  36063.0         NaN
1981     12996923.0        NaN  19943667.0  37502.0         NaN
1982            NaN        NaN  20575701.0  39112.0         NaN
1983            NaN        NaN  21228288.0  40862.0         NaN
1984            NaN  2904429.0  21893857.0  42704.0         NaN
1985            NaN  2964762.0  22565908.0  44597.0   9745209.0
1986            NaN  3022635.0  23241276.0  46515.0  10023700.0
1987            NaN  3083605.0  23917889.0  48458.0  10285712.0
1988            NaN  3142336.0  24591493.0  50431.0  10544904.0
1989            NaN  3227943.0  25257671.0  52449.0  10820992.0
1990            NaN  3286542.0  25912364.0  54511.0  11127870.0
1991            NaN  3266790.0  26554277.0  56674.0  11472173.0
1992            NaN  3247039.0  27180921.0  58904.0  11848971.0
1993            NaN  3227287.0  27785977.0  61003.0  12246786.0
1994            NaN  3207536.0  28362015.0  62707.0  12648483.0
1995            NaN  3187784.0  28904300.0  63854.0  13042666.0
1996            NaN  3168033.0  29411839.0  64291.0  13424813.0
1997            NaN  3148281.0  29887717.0  64147.0  13801868.0
1998            NaN  3128530.0  30336880.0  63888.0  14187710.0
1999            NaN  3108778.0  30766551.0  64161.0  14601983.0
2000            NaN  3089027.0  31183658.0  65399.0  15058638.0
2001     20531160.0  3060173.0  31590320.0  67770.0  15562791.0
2002     21487079.0  3051010.0  31990387.0  71046.0  16109696.0
2003     22507368.0  3039616.0  32394886.0  74783.0  16691395.0
2004     23499850.0  3026939.0  32817225.0  78337.0  17295500.0
2005     24399948.0  3011487.0  33267887.0  81223.0  17912942.0
2006     25183615.0  2992547.0  33749328.0  83373.0  18541467.0
2007     25877544.0  2970017.0  34261971.0  84878.0  19183907.0
2008     26528741.0  2947314.0  34811059.0  85616.0  19842251.0
2009     27207291.0  2927519.0  35401790.0  85474.0  20520103.0
2010     27962207.0  2913021.0  36036159.0  84419.0  21219954.0
2011     28809167.0  2904780.0  36717132.0  82326.0  21942296.0
2012     29726803.0  2900247.0  37439427.0  79316.0  22685632.0
2013     30682500.0  2896652.0  38186135.0  75902.0  23448202.0
2014     31627506.0  2893654.0  38934334.0      NaN  24227524.0
2015     32526562.0  2889167.0  39666519.0      NaN  25021974.0

                                                                           \
country Antigua and Barbuda   Arab World   Argentina    Armenia     Aruba
year
1960                    NaN          NaN         NaN        NaN       NaN
1961                    NaN          NaN         NaN        NaN       NaN
1962                    NaN          NaN  21287682.0        NaN       NaN
1963                    NaN          NaN  21621845.0        NaN       NaN
1964                    NaN          NaN  21953926.0        NaN       NaN
1965                    NaN          NaN  22283389.0        NaN       NaN
1966                    NaN          NaN  22608747.0        NaN       NaN
1967                    NaN          NaN  22932201.0        NaN       NaN
1968                    NaN  115557094.0  23261273.0        NaN       NaN
1969                    NaN  118823872.0  23605992.0        NaN       NaN
1970                    NaN  122128175.0  23973062.0        NaN       NaN
1971                    NaN  125439089.0  24366442.0        NaN       NaN
1972                    NaN  128801209.0  24782950.0        NaN       NaN
1973                    NaN  132298955.0  25213388.0        NaN       NaN
1974                    NaN  136044481.0  25644505.0        NaN       NaN
1975                    NaN  140114424.0  26066975.0        NaN       NaN
1976                    NaN  144542039.0  26477153.0        NaN       NaN
1977                70223.0  149296257.0  26878567.0        NaN       NaN
1978                70508.0  154303887.0  27277742.0        NaN       NaN
1979                70553.0  159455867.0  27684530.0        NaN       NaN
1980                70301.0  164670713.0  28105889.0        NaN       NaN
1981                69750.0  169926632.0  28543366.0        NaN       NaN
1982                68950.0  175237742.0  28993989.0        NaN       NaN
1983                67958.0  180606318.0  29454739.0        NaN       NaN
1984                66863.0  186005735.0  29920907.0        NaN       NaN
1985                65744.0  191564251.0  30388781.0        NaN       NaN
1986                64605.0  197202142.0  30857242.0        NaN       NaN
1987                63484.0  202851923.0  31326473.0        NaN       NaN
1988                62538.0  208546282.0  31795515.0        NaN       NaN
1989                61967.0  214250542.0  32263559.0        NaN       NaN
1990                61906.0  222117305.0  32729740.0  3544695.0       NaN
1991                62412.0  228171034.0  33193920.0  3511912.0       NaN
1992                63434.0  232417246.0  33655149.0  3449497.0       NaN
1993                64868.0  238628852.0  34110912.0  3369673.0       NaN
1994                66550.0  244893420.0  34558114.0  3289943.0   76700.0
1995                68349.0  252591048.0  34994818.0  3223173.0   80326.0
1996                70245.0  258423164.0  35419683.0  3173425.0   83195.0
1997                72232.0  264153948.0  35833965.0  3137652.0   85447.0
1998                74206.0  269795252.0  36241578.0  3112958.0   87276.0
1999                76041.0  275503565.0  36648054.0  3093820.0   89004.0
2000                77648.0  281326250.0  37057453.0  3076098.0   90858.0
2001                78972.0  287291826.0  37471535.0  3060036.0   92894.0
2002                80030.0  293402563.0  37889443.0  3047249.0   94995.0
2003                80904.0  299731956.0  38309475.0  3036420.0   97015.0
2004                81718.0  306387415.0  38728778.0  3025982.0   98742.0
2005                82565.0  313430911.0  39145491.0  3014917.0  100031.0
2006                83467.0  320906736.0  39558750.0  3002161.0  100830.0
2007                84397.0  328766559.0  39969903.0  2988117.0  101218.0
2008                85350.0  336886468.0  40381860.0  2975029.0  101342.0
2009                86300.0  345054176.0  40798641.0  2966108.0  101416.0
2010                87233.0  353112237.0  41222875.0  2963496.0  101597.0
2011                88152.0  361031820.0  41655616.0  2967984.0  101936.0
2012                89069.0  368802611.0  42095224.0  2978339.0       NaN
2013                89985.0  376504253.0  42538304.0  2992192.0       NaN
2014                90900.0  384222592.0  42980026.0  3006154.0       NaN
2015                91818.0  392022276.0         NaN  3017712.0       NaN

         ...           GDP                                            \
country  ...    Uzbekistan       Vanuatu Venezuela, RB       Vietnam
year     ...
1960     ...           NaN           NaN  8.607600e+09           NaN
1961     ...           NaN           NaN  8.923367e+09           NaN
1962     ...           NaN           NaN  9.873398e+09           NaN
1963     ...           NaN           NaN  1.066338e+10           NaN
1964     ...           NaN           NaN  9.113581e+09           NaN
1965     ...           NaN           NaN  9.602945e+09           NaN
1966     ...           NaN           NaN  1.009657e+10           NaN
1967     ...           NaN           NaN  1.047278e+10           NaN
1968     ...           NaN           NaN  1.147091e+10           NaN
1969     ...           NaN           NaN  1.192757e+10           NaN
1970     ...           NaN           NaN  1.299312e+10           NaN
1971     ...           NaN           NaN  1.447156e+10           NaN
1972     ...           NaN           NaN  1.592287e+10           NaN
1973     ...           NaN           NaN  1.944593e+10           NaN
1974     ...           NaN           NaN  2.908710e+10           NaN
1975     ...           NaN           NaN  3.141316e+10           NaN
1976     ...           NaN           NaN  3.627232e+10           NaN
1977     ...           NaN           NaN  4.233706e+10           NaN
1978     ...           NaN           NaN  4.650764e+10           NaN
1979     ...           NaN  1.192588e+08  5.575055e+10           NaN
1980     ...           NaN  1.134232e+08  6.713512e+10           NaN
1981     ...           NaN  9.874641e+07  7.549883e+10           NaN
1982     ...           NaN  9.814464e+07  7.669365e+10           NaN
1983     ...           NaN  1.101238e+08  7.858650e+10           NaN
1984     ...           NaN  1.355538e+08  5.595234e+10           NaN
1985     ...           NaN  1.236985e+08  5.793574e+10  1.409469e+10
1986     ...           NaN  1.186914e+08  5.891511e+10  2.633662e+10
1987     ...           NaN  1.308341e+08  4.534379e+10  3.665811e+10
1988     ...           NaN  1.485454e+08  5.842840e+10  2.542381e+10
1989     ...           NaN  1.444822e+08  4.214230e+10  6.293305e+09
1990     ...  1.336061e+10  1.583974e+08  4.702751e+10  6.471740e+09
1991     ...  1.367762e+10  1.888700e+08  5.173436e+10  9.613370e+09
1992     ...  1.294130e+10  1.961426e+08  5.847036e+10  9.866990e+09
1993     ...  1.309901e+10  1.880804e+08  5.810756e+10  1.318095e+10
1994     ...  1.289916e+10  2.192603e+08  5.652990e+10  1.628643e+10
1995     ...  1.335047e+10  2.339021e+08  7.488874e+10  2.073616e+10
1996     ...  1.394889e+10  2.451776e+08  6.825859e+10  2.465747e+10
1997     ...  1.474460e+10  2.558902e+08  8.583739e+10  2.684370e+10
1998     ...  1.498897e+10  2.623013e+08  9.133854e+10  2.720960e+10
1999     ...  1.707847e+10  2.679992e+08  9.797414e+10  2.868366e+10
2000     ...  1.376037e+10  2.720147e+08  1.171476e+11  3.364009e+10
2001     ...  1.140135e+10  2.579269e+08  1.229097e+11  3.529135e+10
2002     ...  9.687951e+09  2.626038e+08  9.288959e+10  3.794790e+10
2003     ...  1.012811e+10  3.144631e+08  8.362219e+10  4.271707e+10
2004     ...  1.203002e+10  3.649969e+08  1.124514e+11  4.942411e+10
2005     ...  1.430751e+10  3.949626e+08  1.455135e+11  5.763326e+10
2006     ...  1.703090e+10  4.393768e+08  1.834775e+11  6.637166e+10
2007     ...  2.231139e+10  5.264283e+08  2.303642e+11  7.741443e+10
2008     ...  2.793403e+10  6.079586e+08  3.156002e+11  9.913030e+10
2009     ...  3.281683e+10  6.100666e+08  3.294190e+11  1.060146e+11
2010     ...  3.933277e+10  7.008043e+08  3.938015e+11  1.159317e+11
2011     ...  4.532432e+10  7.921497e+08  3.164822e+11  1.355395e+11
2012     ...  5.118344e+10  7.817029e+08  3.812862e+11  1.558200e+11
2013     ...  5.679566e+10  8.017876e+08  3.713366e+11  1.712220e+11
2014     ...  6.313285e+10  8.149546e+08           NaN  1.862047e+11
2015     ...  6.673280e+10           NaN           NaN  1.935994e+11

                                                                              \
country Virgin Islands (U.S.) West Bank and Gaza         World   Yemen, Rep.
year
1960             2.420000e+07                NaN  1.364643e+12           NaN
1961             2.570000e+07                NaN  1.420440e+12           NaN
1962             3.690000e+07                NaN  1.524573e+12           NaN
1963             4.140000e+07                NaN  1.638187e+12           NaN
1964             5.380000e+07                NaN  1.799675e+12           NaN
1965             6.650000e+07                NaN  1.959900e+12           NaN
1966             8.410000e+07                NaN  2.125397e+12           NaN
1967             1.154000e+08                NaN  2.262923e+12           NaN
1968             1.738000e+08                NaN  2.440549e+12           NaN
1969             2.113000e+08                NaN  2.686747e+12           NaN
1970             2.190000e+08                NaN  2.950656e+12           NaN
1971             2.570000e+08                NaN  3.259057e+12           NaN
1972             3.071000e+08                NaN  3.757853e+12           NaN
1973             3.516000e+08                NaN  4.578523e+12           NaN
1974             3.954000e+08                NaN  5.279355e+12           NaN
1975             3.998000e+08                NaN  5.880305e+12           NaN
1976             4.400000e+08                NaN  6.400883e+12           NaN
1977             4.618000e+08                NaN  7.237905e+12           NaN
1978             5.129000e+08                NaN  8.521725e+12           NaN
1979             6.067000e+08                NaN  9.903841e+12           NaN
1980             7.278000e+08                NaN  1.115409e+13           NaN
1981             8.218000e+08                NaN  1.144748e+13           NaN
1982             8.326000e+08                NaN  1.134460e+13           NaN
1983             9.169000e+08                NaN  1.160740e+13           NaN
1984             9.854000e+08                NaN  1.204953e+13           NaN
1985             9.904000e+08                NaN  1.267287e+13           NaN
1986             1.035600e+09                NaN  1.499712e+13           NaN
1987             1.147800e+09                NaN  1.706395e+13           NaN
1988             1.204600e+09                NaN  1.910918e+13           NaN
1989             1.343900e+09                NaN  2.006077e+13           NaN
1990             1.564700e+09                NaN  2.256312e+13  5.647252e+09
1991             1.671200e+09                NaN  2.389846e+13  5.930370e+09
1992             1.770900e+09                NaN  2.537482e+13  6.463650e+09
1993             1.996000e+09                NaN  2.580571e+13  5.368271e+09
1994                      NaN       2.843300e+09  2.770637e+13  4.167356e+09
1995                      NaN       3.282800e+09  3.065894e+13  4.258789e+09
1996                      NaN       3.409600e+09  3.132499e+13  5.785685e+09
1997                      NaN       3.759800e+09  3.124076e+13  6.839039e+09
1998                      NaN       4.067800e+09  3.112270e+13  6.325220e+09
1999                      NaN       4.271200e+09  3.228297e+13  7.641101e+09
2000                      NaN       4.313600e+09  3.332130e+13  9.636342e+09
2001                      NaN       4.003700e+09  3.313421e+13  9.854042e+09
2002                      NaN       3.555800e+09  3.441805e+13  1.069328e+10
2003                      NaN       3.968000e+09  3.865630e+13  1.177777e+10
2004                      NaN       4.329200e+09  4.355213e+13  1.387350e+10
2005                      NaN       4.831800e+09  4.714259e+13  1.675377e+10
2006                      NaN       4.910100e+09  5.107451e+13  1.908173e+10
2007                      NaN       5.505800e+09  5.758343e+13  2.563367e+10
2008                      NaN       6.673500e+09  6.312856e+13  3.039720e+10
2009                      NaN       7.268200e+09  5.983553e+13  2.845950e+10
2010                      NaN       8.913100e+09  6.564782e+13  3.090675e+10
2011                      NaN       1.045985e+10  7.284314e+13  3.107886e+10
2012                      NaN       1.127940e+10  7.442836e+13  3.207477e+10
2013                      NaN       1.247600e+10  7.643132e+13  3.595450e+10
2014                      NaN       1.271560e+10  7.810634e+13           NaN
2015                      NaN       1.267740e+10  7.343364e+13           NaN


country        Zambia      Zimbabwe
year
1960     6.987397e+08  1.052990e+09
1961     6.823597e+08  1.096647e+09
1962     6.792797e+08  1.117602e+09
1963     7.043397e+08  1.159512e+09
1964     8.226397e+08  1.217138e+09
1965     1.061200e+09  1.311436e+09
1966     1.239000e+09  1.281750e+09
1967     1.340639e+09  1.397002e+09
1968     1.573739e+09  1.479600e+09
1969     1.926399e+09  1.747999e+09
1970     1.788779e+09  1.884206e+09
1971     1.653259e+09  2.178716e+09
1972     1.872417e+09  2.677729e+09
1973     2.434255e+09  3.309354e+09
1974     2.910981e+09  3.982161e+09
1975     2.442672e+09  4.371301e+09
1976     2.742859e+09  4.318372e+09
1977     2.515297e+09  4.364382e+09
1978     2.811032e+09  4.351600e+09
1979     3.353445e+09  5.177459e+09
1980     3.884531e+09  6.678868e+09
1981     4.008126e+09  8.011374e+09
1982     3.871117e+09  8.539701e+09
1983     3.321048e+09  7.764067e+09
1984     2.719519e+09  6.352126e+09
1985     2.252455e+09  5.637259e+09
1986     1.664414e+09  6.217524e+09
1987     2.265251e+09  6.741215e+09
1988     3.728878e+09  7.814784e+09
1989     3.994673e+09  8.286323e+09
1990     3.288382e+09  8.783817e+09
1991     3.378882e+09  8.641482e+09
1992     3.181922e+09  6.751472e+09
1993     3.273238e+09  6.563813e+09
1994     3.656648e+09  6.890675e+09
1995     3.807067e+09  7.111271e+09
1996     3.597221e+09  8.553147e+09
1997     4.303282e+09  8.529572e+09
1998     3.537683e+09  6.401968e+09
1999     3.404312e+09  6.858013e+09
2000     3.600683e+09  6.689958e+09
2001     4.094481e+09  6.777385e+09
2002     4.193846e+09  6.342116e+09
2003     4.901840e+09  5.727592e+09
2004     6.221078e+09  5.805598e+09
2005     8.331870e+09  5.755215e+09
2006     1.275686e+10  5.443896e+09
2007     1.405696e+10  5.291950e+09
2008     1.791086e+10  4.415703e+09
2009     1.532834e+10  8.157077e+09
2010     2.026555e+10  9.422161e+09
2011     2.345952e+10  1.095623e+10
2012     2.550306e+10  1.239272e+10
2013     2.804552e+10  1.349023e+10
2014     2.713464e+10  1.419691e+10
2015     2.120156e+10  1.389294e+10

[56 rows x 504 columns]

In [32]:
world.unstack([1,0]).to_frame()

                                               0
           country            year
Population Afghanistan        1960  8.994793e+06
           Algeria            1960  1.112489e+07
           Australia          1960  1.027648e+07
           Austria            1960  7.047539e+06
           Bahamas, The       1960  1.095260e+05
...                                          ...
GDP        Vietnam            2015  1.935994e+11
           West Bank and Gaza 2015  1.267740e+10
           World              2015  7.343364e+13
           Zambia             2015  2.120156e+10
           Zimbabwe           2015  1.389294e+10

[22422 rows x 1 columns]

In [33]:
world.unstack(["country","year"])

            country             year
Population  Afghanistan         1960    8.994793e+06
            Algeria             1960    1.112489e+07
            Australia           1960    1.027648e+07
            Austria             1960    7.047539e+06
            Bahamas, The        1960    1.095260e+05
                                            ...
GDP         Vietnam             2015    1.935994e+11
            West Bank and Gaza  2015    1.267740e+10
            World               2015    7.343364e+13
            Zambia              2015    2.120156e+10
            Zimbabwe            2015    1.389294e+10
Length: 22422, dtype: float64

In [34]:
world.unstack(["year","country"])

            year  country
Population  1960  Afghanistan           8.994793e+06
                  Algeria               1.112489e+07
                  Australia             1.027648e+07
                  Austria               7.047539e+06
                  Bahamas, The          1.095260e+05
                                            ...
GDP         2015  Vietnam               1.935994e+11
                  West Bank and Gaza    1.267740e+10
                  World                 7.343364e+13
                  Zambia                2.120156e+10
                  Zimbabwe              1.389294e+10
Length: 22422, dtype: float64

In [36]:
world.unstack(["year","country"]).sort_index()

            year  country
GDP         1960  Afghanistan           5.377778e+08
                  Algeria               2.723638e+09
                  Australia             1.856759e+10
                  Austria               6.592694e+09
                  Bahamas, The          1.698023e+08
                                            ...
Population  2015  Vietnam               9.170380e+07
                  West Bank and Gaza    4.422143e+06
                  World                 7.346633e+09
                  Zambia                1.621177e+07
                  Zimbabwe              1.560275e+07
Length: 22422, dtype: float64

In [40]:
#The pivot method

sales = pd.read_csv("salesmen.csv")
sales

          Date Salesman  Revenue
0       1/1/16      Bob     7172
1       1/2/16      Bob     6362
2       1/3/16      Bob     5982
3       1/4/16      Bob     7917
4       1/5/16      Bob     7837
...        ...      ...      ...
1825  12/27/16    Oscar      835
1826  12/28/16    Oscar     3073
1827  12/29/16    Oscar     6424
1828  12/30/16    Oscar     7088
1829  12/31/16    Oscar     8408

[1830 rows x 3 columns]

In [44]:
sales.pivot(index="Date", columns="Salesman", values="Revenue")

Salesman   Bob  Dave   Jeb  Oscar  Ronald
Date
1/1/16    7172  1864  4430   5250    2639
1/10/16   7543  7105   301   7663    8267
1/11/16   1053  6851  9489   8888    1340
1/12/16   4362  7147  8719   3092     279
1/13/16   6812  6160  2349   6139    7540
...        ...   ...   ...    ...     ...
9/5/16     992   211  2439   7743    4252
9/6/16     556  7293  7585   5072    1112
9/7/16    6499  9774  6669   5230    3608
9/8/16    9621  8194  3058   7755    5762
9/9/16    1231  4733  6823   5684    8922

[366 rows x 5 columns]

In [47]:
# The melt Method

quarters = pd.read_csv("quarters.csv")
quarters

  Salesman      Q1      Q2      Q3      Q4
0    Boris  602908  233879  354479   32704
1      Bob   43790  514863  297151  544493
2    Tommy  392668  113579  430882  247231
3   Travis  834663  266785  749238  570524
4   Donald  580935  411379  110390  651572
5      Ted  656644   70803  375948  321388
6      Jeb  486141  600753  742716  404995
7    Stacy  479662  742806  770712    2501
8   Morgan  992673  879183   37945  293710

In [51]:
quarters.melt(id_vars="Salesman", var_name="Quarter", value_name="Revenue")

   Salesman Quarter  Revenue
0     Boris      Q1   602908
1       Bob      Q1    43790
2     Tommy      Q1   392668
3    Travis      Q1   834663
4    Donald      Q1   580935
5       Ted      Q1   656644
6       Jeb      Q1   486141
7     Stacy      Q1   479662
8    Morgan      Q1   992673
9     Boris      Q2   233879
10      Bob      Q2   514863
11    Tommy      Q2   113579
12   Travis      Q2   266785
13   Donald      Q2   411379
14      Ted      Q2    70803
15      Jeb      Q2   600753
16    Stacy      Q2   742806
17   Morgan      Q2   879183
18    Boris      Q3   354479
19      Bob      Q3   297151
20    Tommy      Q3   430882
21   Travis      Q3   749238
22   Donald      Q3   110390
23      Ted      Q3   375948
24      Jeb      Q3   742716
25    Stacy      Q3   770712
26   Morgan      Q3    37945
27    Boris      Q4    32704
28      Bob      Q4   544493
29    Tommy      Q4   247231
30   Travis      Q4   570524
31   Donald      Q4   651572
32      Ted      Q4   321388
33      Jeb      Q4   404995
34    Stacy      Q4     2501
35   Morgan      Q4   293710

In [ ]:
# The pivot_table Method

food = pd.read_csv("foods.csv")

food.head()

  First Name  Gender          City Frequency       Item  Spend
0      Wanda  Female      Stamford    Weekly     Burger  15.66
1       Eric    Male      Stamford     Daily    Chalupa  10.56
2    Charles    Male      New York     Never      Sushi  42.14
3       Anna  Female  Philadelphia      Once  Ice Cream  11.01
4    Deborah  Female  Philadelphia     Daily    Chalupa  23.49

In [ ]:
# Media

food.pivot_table(values="Spend", index="Gender")

            Spend
Gender
Female  50.709629
Male    49.397623

In [ ]:
# agregar una funcion
food.pivot_table(values="Spend", index="Gender", aggfunc="mean")

            Spend
Gender
Female  50.709629
Male    49.397623

In [ ]:
# sumar valores
food.pivot_table(values="Spend", index="Gender", aggfunc="sum")

           Spend
Gender
Female  25963.33
Male    24106.04

In [ ]:
# valores de gasos para cada articulo
# cuanto se ha vendido por producto

food.pivot_table(values="Spend", index="Item", aggfunc="sum")

             Spend
Item
Burger     7765.73
Burrito    8270.44
Chalupa    7644.52
Donut      8758.76
Ice Cream  8886.99
Sushi      8742.93

In [ ]:
# por grupo y por articulo: suma acumulada de los gastos para cada combinacion de sexo y articulo

food.pivot_table(values="Spend", index=["Gender","Item"], aggfunc="sum")

                    Spend
Gender Item
Female Burger     4094.30
       Burrito    4257.82
       Chalupa    4152.26
       Donut      4743.00
       Ice Cream  4032.87
       Sushi      4683.08
Male   Burger     3671.43
       Burrito    4012.62
       Chalupa    3492.26
       Donut      4015.76
       Ice Cream  4854.12
       Sushi      4059.85

In [61]:
food.pivot_table(values="Spend", index=["Gender","Item"], columns="City", aggfunc="sum")

City              New York  Philadelphia  Stamford
Gender Item
Female Burger      1239.04       1639.24   1216.02
       Burrito      978.95       1458.76   1820.11
       Chalupa      876.58       1673.33   1602.35
       Donut       1446.78       1639.26   1656.96
       Ice Cream   1521.62       1479.22   1032.03
       Sushi       1480.29       1742.88   1459.91
Male   Burger      1294.09        938.18   1439.16
       Burrito     1399.40       1312.93   1300.29
       Chalupa     1227.77       1114.23   1150.26
       Donut       1345.27       1249.36   1421.13
       Ice Cream   1603.63       2191.27   1059.22
       Sushi       1396.15       1395.88   1267.82

In [62]:
food.pivot_table(values="Spend", index="Item", columns=["Gender", "City"], aggfunc="sum")

Gender      Female                           Male
City      New York Philadelphia Stamford New York Philadelphia Stamford
Item
Burger     1239.04      1639.24  1216.02  1294.09       938.18  1439.16
Burrito     978.95      1458.76  1820.11  1399.40      1312.93  1300.29
Chalupa     876.58      1673.33  1602.35  1227.77      1114.23  1150.26
Donut      1446.78      1639.26  1656.96  1345.27      1249.36  1421.13
Ice Cream  1521.62      1479.22  1032.03  1603.63      2191.27  1059.22
Sushi      1480.29      1742.88  1459.91  1396.15      1395.88  1267.82

In [63]:
food.pivot_table(values="Spend", index="Item", columns=["Gender", "City"], aggfunc="count")

Gender      Female                           Male
City      New York Philadelphia Stamford New York Philadelphia Stamford
Item
Burger          24           31       27       22           21       31
Burrito         23           28       34       25           30       28
Chalupa         19           32       25       25           23       23
Donut           31           30       34       30           33       29
Ice Cream       27           32       22       29           41       25
Sushi           31           30       32       27           28       18

In [64]:
food.pivot_table(values="Spend", index="Item", columns=["Gender", "City"], aggfunc="max")

Gender      Female                           Male
City      New York Philadelphia Stamford New York Philadelphia Stamford
Item
Burger       98.96        97.79    85.06    90.32        99.68    97.20
Burrito      92.25        96.79    99.21    98.04        93.27    95.07
Chalupa      98.43        99.29    98.78    96.44        98.40    99.87
Donut        95.63        96.52    91.75    86.70        93.12    99.26
Ice Cream    97.83        88.14    97.44    97.65        99.24    99.17
Sushi        99.51        99.02    95.43    93.85        97.12    98.48

In [65]:
food.pivot_table(values="Spend", index="Item", columns=["Gender", "City"], aggfunc="min")

Gender      Female                           Male
City      New York Philadelphia Stamford New York Philadelphia Stamford
Item
Burger        2.25         1.97     6.24     5.43         1.71     2.83
Burrito       1.02         1.04     1.18    15.90         8.58     3.64
Chalupa       1.96         9.35     9.09    11.61         1.94    10.56
Donut         3.15         2.13     1.68     1.49         1.26     6.63
Ice Cream    13.39         7.61     8.80    14.06         4.89     3.43
Sushi         2.52        11.68     8.20     3.28         2.01    32.15

In [67]:
food.pivot_table(values="Spend", index="Item", columns=["Gender", "City"], aggfunc="std")

Gender        Female                               Male               \
City        New York Philadelphia   Stamford   New York Philadelphia
Item
Burger     33.432291    29.357528  24.264654  23.087229    32.268256
Burrito    30.750133    27.985756  27.492440  22.562802    23.443954
Chalupa    29.198219    26.238557  25.497616  26.952377    29.843290
Donut      27.232037    29.501886  26.532465  25.838065    27.883722
Ice Cream  26.358787    25.296960  27.828017  27.894260    29.018596
Sushi      30.671688    25.398754  25.230179  27.171989    28.163608

Gender
City        Stamford
Item
Burger     29.450094
Burrito    29.817623
Chalupa    28.735567
Donut      29.678526
Ice Cream  27.068875
Sushi      21.060369