In [1]:
import pandas as pd

In [2]:
bond = pd.read_csv('jamesbond.csv')
# bond = pd.read_csv('jamesbond.csv', index_col='Film')
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [44]:
# The set_index and reset_index Methods
bond = bond.set_index("Film")
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [45]:
bond.reset_index()
bond.reset_index(drop=True)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [46]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [50]:
bond.set_index("Year")

,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,
1962,Sean Connery,Terence Young,448.8,7.0,0.6
1963,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Sean Connery,Terence Young,848.1,41.9,4.7
1967,David Niven,Ken Hughes,315.0,85.0,NaN
1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
1981,Roger Moore,John Glen,449.4,60.2,NaN
1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
1983,Roger Moore,John Glen,373.8,53.9,7.8
1985,Roger Moore,John Glen,275.2,54.5,9.1
1987,Timothy Dalton,John Glen,313.5,68.8,5.2
1989,Timothy Dalton,John Glen,250.9,56.7,7.9
1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [53]:
bond = bond.reset_index().set_index("Year")

In [54]:
bond.head()

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN

In [63]:
# Retrieve rows by index position with iloc accessor

bond = pd.read_csv("jamesbond.csv")
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [65]:
# es el número de la posicion
bond.iloc[4]
bond.iloc[[15,20]]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5

In [67]:
# desde el 4 sin incluir el 8
bond.iloc[4:8]

# desde el 0 al 6, sin incluir el 6
bond.iloc[0:6]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [3]:
# Retrieve Rows by Index Label with loc Accessor

bond = pd.read_csv("jamesbond.csv", index_col = "Film")
bond.head()
bond.loc["Goldfinger"]

Year                         1964
Actor                Sean Connery
Director             Guy Hamilton
Box Office                  820.4
Budget                       18.6
Bond Actor Salary             3.2
Name: Goldfinger, dtype: object

In [4]:
bond.loc["GoldenEye"]

Year                            1995
Actor                 Pierce Brosnan
Director             Martin Campbell
Box Office                     518.5
Budget                          76.9
Bond Actor Salary                5.1
Name: GoldenEye, dtype: object

In [5]:
bond.loc["Casino Royale"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3

In [9]:
bond.loc[["Octopussy","Moonraker","Casino Royale"]]

# Si no exite un valor dara error

bond.loc[["Octopussy","Moonraker","Casino Royale","Gold Bond"]]

KeyError: "['Gold Bond'] not in index"

In [ ]:
# Index positions: extrae desde "Diamonds are forever" hasta "moonraker"

bond.loc["Diamonds Are Forever":"Moonraker"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [11]:
bond.loc[:"On Her Majesty's Secret Service"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6

In [12]:
bond.loc["GoldenEye":]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [14]:
bond.loc[:"Casino Royale"]

KeyError: "Cannot get right slice bound for non-unique label: 'Casino Royale'"

In [1]:
import pandas as pd
import numpy as np
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
# Extraer un valor con una condicion especifica

bond.loc["Diamonds Are Forever", "Director"]

'Guy Hamilton'

In [ ]:
bond.loc[["Octopussy", "GoldenEye"],"Director"]

Film
Octopussy          John Glen
GoldenEye    Martin Campbell
Name: Director, dtype: object

In [23]:
bond.loc["GoldenEye":"Octopussy","Director":"Budget"]

                              Director  Box Office  Budget
Film
GoldenEye              Martin Campbell       518.5    76.9
Goldfinger                Guy Hamilton       820.4    18.6
Licence to Kill              John Glen       250.9    56.7
Live and Let Die          Guy Hamilton       460.3    30.8
Moonraker                Lewis Gilbert       535.0    91.5
Never Say Never Again   Irvin Kershner       380.0    86.0
Octopussy                    John Glen       373.8    53.9

In [25]:
bond.loc["GoldenEye":"Octopussy", ["Actor","Bond Actor Salary","Year"]]

                                Actor  Bond Actor Salary  Year
Film
GoldenEye              Pierce Brosnan                5.1  1995
Goldfinger               Sean Connery                3.2  1964
Licence to Kill        Timothy Dalton                7.9  1989
Live and Let Die          Roger Moore                NaN  1973
Moonraker                 Roger Moore                NaN  1979
Never Say Never Again    Sean Connery                NaN  1983
Octopussy                 Roger Moore                7.8  1983

In [26]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [ ]:
bond.iloc[0,2]

bond.iloc[3,5]

bond.iloc[[0,2],3]

bond.iloc[:7,:3]

# loc busca por etiqueta, mientras iloc busca por posicion de indice

                      Year           Actor         Director
Film
A View to a Kill      1985     Roger Moore        John Glen
Casino Royale         2006    Daniel Craig  Martin Campbell
Casino Royale         1967     David Niven       Ken Hughes
Diamonds Are Forever  1971    Sean Connery     Guy Hamilton
Die Another Day       2002  Pierce Brosnan     Lee Tamahori
Dr. No                1962    Sean Connery    Terence Young
For Your Eyes Only    1981     Roger Moore        John Glen

In [8]:
# Reemplazo de un valor
bond["Actor"].loc["Diamonds Are Forever"] = "Sir Sean Connery"

C:\Users\johan\AppData\Local\Temp\ipykernel_17820\873675113.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bond["Actor"].loc["Diamonds Are Forever"] = "Sir Sean Connery"

In [12]:
bond.loc["Diamonds Are Forever","Actor"] = "Sir Sean Connery"
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [49]:
import pandas as pd
import numpy as np
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
#Solucion mas facil para reemplazar varios valores

bond["Actor"] = bond["Actor"].replace("Sean Connery","Sir Sean Connery")

In [38]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [50]:
bond[bond["Actor"] == "Sean Connery"].loc[:,"Actor"] = "Sir Sean Connery"

In [51]:
is_sean_connery = bond["Actor"] == "Sean Connery"
bond.loc[is_sean_connery,"Actor"] = "Sir Sean Connery"
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [52]:
# Rename Index Labels or Columns in a DataFrame

bond = pd.read_csv("jamesbond.csv",index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [54]:
bond = bond.rename(columns={"Year": "Year of Release", "Box Office":"Revenue"})
bond.head()

,Year of Release,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
#Reemplazar valores del indice
swaps = {
    "Dr. No" :"Dr No",
    "GoldenEye": "Golden Eye",
    "The World Is Not Enough" : "Best Bond Movie Ever"

}
bond = bond.rename(index=swaps)
bond.head()

,Year of Release,Actor,Director,Revenue,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [ ]:
# Metodo ordenado sort_index()

In [59]:
bond.columns = ["Year","Bond Guy","Camera Dude","Revenues","Cost","Salary"]

In [60]:
bond

,Year,Bond Guy,Camera Dude,Revenues,Cost,Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Golden Eye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
Best Bond Movie Ever,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [ ]:
#bond.columns[3] = "The Money"

TypeError: Index does not support mutable operations

In [69]:
#Delete Rows or Columns from a DataFrame
bond = pd.read_csv("jamesbond.csv",index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [70]:
bond.drop(columns=["Box Office","Budget"])
bond.drop(index=["Casino Royale"])


bond.drop(index=["Casino Royale"],columns=["Box Office","Budget"])

,Year,Actor,Director,Bond Actor Salary
Film,,,,
A View to a Kill,1985,Roger Moore,John Glen,9.1
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,17.9
Dr. No,1962,Sean Connery,Terence Young,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,NaN
From Russia with Love,1963,Sean Connery,Terence Young,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,NaN
Octopussy,1983,Roger Moore,John Glen,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,14.5
Spectre,2015,Daniel Craig,Sam Mendes,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,13.5
Thunderball,1965,Sean Connery,Terence Young,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,4.4

In [71]:
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [72]:
actor = bond.pop("Actor")
actor.head()

Film
A View to a Kill           Roger Moore
Casino Royale             Daniel Craig
Casino Royale              David Niven
Diamonds Are Forever      Sean Connery
Die Another Day         Pierce Brosnan
Name: Actor, dtype: object

In [ ]:
#Mayusculas y minusculas son importantes al momento de coincidir con el DF
del bond ["Year"]

bond.head()

                             Director  Box Office  Budget  Bond Actor Salary
Film
A View to a Kill            John Glen       275.2    54.5                9.1
Casino Royale         Martin Campbell       581.5   145.3                3.3
Casino Royale              Ken Hughes       315.0    85.0                NaN
Diamonds Are Forever     Guy Hamilton       442.5    34.7                5.8
Die Another Day          Lee Tamahori       465.4   154.2               17.9

In [74]:
bond = pd.read_csv("jamesbond.csv",index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [77]:
bond.sample(n=5)
bond.sample(n=3, axis ='rows')
bond.sample(n=2, axis ='columns')

                                 Year           Actor
Film
A View to a Kill                 1985     Roger Moore
Casino Royale                    2006    Daniel Craig
Casino Royale                    1967     David Niven
Diamonds Are Forever             1971    Sean Connery
Die Another Day                  2002  Pierce Brosnan
Dr. No                           1962    Sean Connery
For Your Eyes Only               1981     Roger Moore
From Russia with Love            1963    Sean Connery
GoldenEye                        1995  Pierce Brosnan
Goldfinger                       1964    Sean Connery
Licence to Kill                  1989  Timothy Dalton
Live and Let Die                 1973     Roger Moore
Moonraker                        1979     Roger Moore
Never Say Never Again            1983    Sean Connery
Octopussy                        1983     Roger Moore
On Her Majesty's Secret Service  1969  George Lazenby
Quantum of Solace                2008    Daniel Craig
Skyfall                          2012    Daniel Craig
Spectre                          2015    Daniel Craig
The Living Daylights             1987  Timothy Dalton
The Man with the Golden Gun      1974     Roger Moore
The Spy Who Loved Me             1977     Roger Moore
The World Is Not Enough          1999  Pierce Brosnan
Thunderball                      1965    Sean Connery
Tomorrow Never Dies              1997  Pierce Brosnan
You Only Live Twice              1967    Sean Connery

In [78]:
# The nsmallest and nlargest Methods

bond = pd.read_csv("jamesbond.csv",index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [79]:
bond.sort_values("Box Office",ascending=False).head(4)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [80]:
bond.nlargest(n=4,columns="Box Office")

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [81]:
bond["Box Office"].nlargest(4)

Film
Skyfall        943.5
Thunderball    848.1
Goldfinger     820.4
Spectre        726.7
Name: Box Office, dtype: float64

In [ ]:
# arroja los valores mas pequeños de la columna X
bond.nsmallest(3, columns="Bond Actor Salary")
bond["Bond"]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6

In [3]:
# encontrar las filas mas grandes basandose en los valores

bond.nlargest(n=2, columns="Actor" )

TypeError: Column 'Actor' has dtype object, cannot use method 'nlargest' with this dtype

In [4]:
# FIltering with the where Method
bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [7]:
actor_is_sean_connery = bond["Actor"] == "Sean Connery"
bond[actor_is_sean_connery]
bond.loc[actor_is_sean_connery]
bond.where(actor_is_sean_connery)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Casino Royale,NaN,NaN,NaN,NaN,NaN,NaN
Diamonds Are Forever,1971.0,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,NaN,NaN,NaN,NaN,NaN,NaN
Dr. No,1962.0,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,NaN,NaN,NaN,NaN,NaN,NaN
From Russia with Love,1963.0,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,NaN,NaN,NaN,NaN,NaN,NaN
Goldfinger,1964.0,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,NaN,NaN,NaN,NaN,NaN,NaN
Live and Let Die,NaN,NaN,NaN,NaN,NaN,NaN
Moonraker,NaN,NaN,NaN,NaN,NaN,NaN
Never Say Never Again,1983.0,Sean Connery,Irvin Kershner,380.0,86.0,NaN
Octopussy,NaN,NaN,NaN,NaN,NaN,NaN
On Her Majesty's Secret Service,NaN,NaN,NaN,NaN,NaN,NaN
Quantum of Solace,NaN,NaN,NaN,NaN,NaN,NaN
Skyfall,NaN,NaN,NaN,NaN,NaN,NaN
Spectre,NaN,NaN,NaN,NaN,NaN,NaN
The Living Daylights,NaN,NaN,NaN,NaN,NaN,NaN
The Man with the Golden Gun,NaN,NaN,NaN,NaN,NaN,NaN
The Spy Who Loved Me,NaN,NaN,NaN,NaN,NaN,NaN
The World Is Not Enough,NaN,NaN,NaN,NaN,NaN,NaN
Thunderball,1965.0,Sean Connery,Terence Young,848.1,41.9,4.7
Tomorrow Never Dies,NaN,NaN,NaN,NaN,NaN,NaN
You Only Live Twice,1967.0,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [10]:
#Apply method with dataframe

bond = pd.read_csv("jamesbond.csv", index_col="Film").sort_index()
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [12]:
bond["Actor"].apply(len)

Film
A View to a Kill                   11
Casino Royale                      12
Casino Royale                      11
Diamonds Are Forever               12
Die Another Day                    14
Dr. No                             12
For Your Eyes Only                 11
From Russia with Love              12
GoldenEye                          14
Goldfinger                         12
Licence to Kill                    14
Live and Let Die                   11
Moonraker                          11
Never Say Never Again              12
Octopussy                          11
On Her Majesty's Secret Service    14
Quantum of Solace                  12
Skyfall                            12
Spectre                            12
The Living Daylights               14
The Man with the Golden Gun        11
The Spy Who Loved Me               11
The World Is Not Enough            14
Thunderball                        12
Tomorrow Never Dies                14
You Only Live Twice                12
Name: Actor, dtype: int64

In [13]:
bond.head(1)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1

In [15]:
def rank_movie(row):
    year = row.loc["Year"]
    actor = row.loc ["Actor"]
    budget = row.loc ["Budget"]

    if year >= 1980 and year < 1990:
        return "Great 80's flick!"
    if actor == "Pierce Brosnan":
        return "The best Bond ever"
    if budget >100:
        return "Expensive movie, fun"  
    return "No comment"


bond.apply(rank_movie, axis="columns")

Film
A View to a Kill                      Great 80's flick!
Casino Royale                      Expensive movie, fun
Casino Royale                                No comment
Diamonds Are Forever                         No comment
Die Another Day                      The best Bond ever
Dr. No                                       No comment
For Your Eyes Only                    Great 80's flick!
From Russia with Love                        No comment
GoldenEye                            The best Bond ever
Goldfinger                                   No comment
Licence to Kill                       Great 80's flick!
Live and Let Die                             No comment
Moonraker                                    No comment
Never Say Never Again                 Great 80's flick!
Octopussy                             Great 80's flick!
On Her Majesty's Secret Service              No comment
Quantum of Solace                  Expensive movie, fun
Skyfall                            Expensive movie, fun
Spectre                            Expensive movie, fun
The Living Daylights                  Great 80's flick!
The Man with the Golden Gun                  No comment
The Spy Who Loved Me                         No comment
The World Is Not Enough              The best Bond ever
Thunderball                                  No comment
Tomorrow Never Dies                  The best Bond ever
You Only Live Twice                          No comment
dtype: object